---
# Copyright (c) 2021-2024 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# Variable distribution_id is a list which uniquely identifies a distribution release, e.g.
#  ['CentOS', '8'] for CentOS 8 (both Core and Stream)
#  ['Debian', '10'] for Debian 10 (Buster)
#  ['Red Hat Enterprise Linux', '8' ]` for Red Hat Enterprise Linux (RHEL) 8
#  ['Ubuntu', '20.04' ] for Ubuntu 20.04 LTS (Focal Fossa)
#
# NOTE: Version numbers for upcoming Debian releases are not stable. For example, when lsb_release is available, which
# is the default, Ansible will report 'n/a' for Debian's testing and unstable (Sid) distributions. When lsb_release
# has been uninstalled, the version string will be 'trixie/sid' or similar. In the past, 'NA' would be reported when
# lsb_release was not available and 'testing' or 'sid' when it was installed.
distribution_id:
- '{{ ansible_facts.distribution }}'
- # Use major and minor version for Ubuntu, e.g. Ubuntu 18.04 LTS (Bionic Beaver) or Ubuntu 20.04 LTS (Focal Fossa).
  # Use major version for all other distributions, e.g. CentOS 7, Debian 10 (Buster) or Red Hat Enterprise Linux 8.
  "{{ ansible_facts.distribution_version if ansible_facts.distribution == 'Ubuntu' else
      ansible_facts.distribution_major_version }}"

# pxe_hwfp_daemon_host is set in host_vars

pxe_hwfp_daemon_group: nogroup

pxe_hwfp_daemon_port: 8000

pxe_hwfp_daemon_user: hwfp

pxe_hwfp_distribution_filename_map:
  x86_64:
    UEFI: 'hwfp/amd64/debian-installer/amd64/bootnetx64.efi'
    BIOS: 'hwfp/amd64/pxelinux.0'

pxe_hwfp_files_amd64:
  'https://deb.debian.org/debian/dists/bullseye/main/installer-amd64/current/images/netboot/netboot.tar.gz'

pxe_hwfp_kernel_parameters: ''

# NOTE: Base path of tftpd which points to scheme://authority/.
pxe_hwfp_tftpd_root: |-
  {{
    {
      'CentOS':                   '/var/lib/tftpboot',
      'Debian':                   '/srv/tftp',
      'Fedora':                   '/var/lib/tftpboot',
      'Red_Hat_Enterprise_Linux': '/var/lib/tftpboot',
      'Ubuntu':                   '/srv/tftp'
    }[distribution_id | first | regex_replace('[^A-Za-z0-9_]', '_')]
  }}

pxe_hwfp_virtualenv: /opt/hwfp_venv/
