---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

cloudinit_metadata: '{{ omit }}'

cloudinit_networkconfig: '{{ omit }}'

cloudinit_userdata: !!null # is set in host_vars

libvirt_configdrive: '{{ inventory_hostname }}_cidata.{{ libvirt_configdrive_format }}'

libvirt_configdrive_filesystem: 'iso'

libvirt_configdrive_format: 'qcow2'

libvirt_configdrive_pool: 'default'

libvirt_domain: '{{ inventory_hostname }}'

libvirt_domain_autostart: no

# Possible domain states: [running, paused, pmsuspended, shutoff]
# Ref.: https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainState
libvirt_domain_state: running

libvirt_hardware: '{{ omit }}'

libvirt_uri: 'qemu:///system'

state: present
