---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: 'Store iptables rules on CentOS and Red Hat Enterprise Linux'
  when: distribution_id|first in ['CentOS', 'Red Hat Enterprise Linux'] and
        iptables_service_state not in ['stopped', 'absent'] and
        iptables_persistence
  command: service iptables save # noqa command-instead-of-module

- name: 'Store iptables rules on Debian and Ubuntu'
  when: distribution_id|first in ['Debian', 'Ubuntu'] and
        iptables_service_state not in ['stopped', 'absent'] and
        iptables_persistence
  command: netfilter-persistent save
