---
# Copyright (c) 2021-2024 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: 'Store iptables rules on CentOS, Fedora and Red Hat Enterprise Linux'
  when: distribution_id | first in ['CentOS', 'Fedora', 'Red Hat Enterprise Linux'] and
        iptables_service_state not in ['stopped', 'absent'] and iptables_persistence
  ansible.builtin.command:
    cmd: /usr/libexec/iptables/iptables.init save
  changed_when: true

- name: 'Store ip6tables rules on CentOS, Fedora and Red Hat Enterprise Linux'
  when: distribution_id | first in ['CentOS', 'Fedora', 'Red Hat Enterprise Linux'] and
        ip6tables_service_state not in ['stopped', 'absent'] and iptables_persistence
  ansible.builtin.command:
    cmd: /usr/libexec/iptables/ip6tables.init save
  changed_when: true

- name: 'Store iptables rules on Debian and Ubuntu'
  when: distribution_id | first in ['Debian', 'Ubuntu'] and iptables_persistence
  ansible.builtin.command:
    cmd: netfilter-persistent save
  changed_when: true
