---
# Copyright (c) 2020-2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Add/Remove compute flavors from OpenStack
  loop: '{{ openstack_compute_flavors|default([]) }}'
  openstack.cloud.compute_flavor: "{{ item
    |dict2items|rejectattr('key', 'eq', 'projects')|list|items2dict
    |combine({} if 'auth' in item else {'auth': openstack_auth})
    |combine({} if 'cloud' in item else {'cloud': openstack_cloud})
    |combine({} if 'interface' in item else {'interface': openstack_interface})
  }}"

- name: Match compute flavors and projects
  set_fact:
    items: '{{ [item]|product(item.projects|default([]))|list }}'
  loop: '{{ openstack_compute_flavors|default([]) }}'
  register: openstack_compute_flavors_per_project

- name: Postprocess compute flavors and projects
  set_fact:
    openstack_compute_flavors_per_project:
     "{{ openstack_compute_flavors_per_project.results|map(attribute='ansible_facts.items')|default([])|flatten(levels=1)|list }}"

- name: Retrieve info about OpenStack projects
  loop: "{{ openstack_compute_flavors_per_project }}"
  openstack.cloud.project_info:
    auth: "{{ item.0.auth if 'auth' in item.0 else openstack_auth }}"
    cloud: "{{ item.0.cloud if 'cloud' in item.0 else openstack_cloud }}"
    interface: "{{ item.0.interface if 'interface' in item.0 else openstack_interface }}"
    name: '{{ item.1.name|mandatory }}'
    # might return more than one project per project name if project name is ambiguous
  register: openstack_project_info

- name: Match compute flavors and project info
  loop: '{{ openstack_compute_flavors_per_project|zip(openstack_project_info.results)|list }}'
  set_fact:
    items: '{{ [item.0]|product(item.1.openstack_projects|default([]))|list }}'
  register: openstack_compute_flavors_per_project_info

- name: Postprocess compute flavors and project info
  set_fact:
    openstack_compute_flavors_per_project_info:
     "{{ openstack_compute_flavors_per_project_info.results|map(attribute='ansible_facts.items')|default([])|flatten(levels=1)|list }}"

- name: Add/Remove compute flavors access from OpenStack projects
  loop: '{{ openstack_compute_flavors_per_project_info }}'
  openstack.cloud.project_access:
    auth: "{{ item.0.0.auth if 'auth' in item.0.0 else openstack_auth }}"
    cloud: "{{ item.0.0.cloud if 'cloud' in item.0.0 else openstack_cloud }}"
    interface: "{{ item.0.0.interface if 'interface' in item.0.0 else openstack_interface }}"
    resource_name: '{{ item.0.0.name }}'
    resource_type: 'nova_flavor'
    target_project_id: '{{ item.1.id }}'
    state: '{{ item.0.1.state }}'
  when: item.0.0.state|default('present') == 'present'
