---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Toggle SELinux booleans
  loop: '{{ selinux_config|default([]) }}'
  when: "'seboolean' in item"
  seboolean: "{{ item['seboolean'] }}"
  register: selinux_config_seboolean_result

- name: Change policy and state of SELinux
  loop: '{{ selinux_config|default([]) }}'
  when: "'selinux' in item"
  selinux: "{{ item['selinux'] }}"
  register: selinux_config_selinux_result

- name: Debug role variables
  debug:
    msg:
      selinux_config_seboolean_result: '{{ selinux_config_seboolean_result }}'
      selinux_config_selinux_result: '{{ selinux_config_selinux_result }}'
  tags:
    - never
    - debug
