---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Install dependencies of collection jm1.pkg
  import_role:
    name: jm1.pkg.setup # If Ansible raises "ERROR! the role 'jm1.pkg.setup' was not found" then you might use the
                        # ansible-galaxy and the provided requirements.yml to install all missing role dependencies.

- name: Satisfy requirements on CentOS and Red Hat Enterprise Linux
  when: distribution_id|first in ['CentOS', 'Red Hat Enterprise Linux']
  jm1.pkg.meta_pkg:
    name: "jm1-cloudy-tftpd"
    version: "1"
    depends:
    - tftp-server

- name: Satisfy requirements on Debian and Ubuntu
  when: distribution_id|first in ['Debian', 'Ubuntu']
  jm1.pkg.meta_pkg:
    name: "jm1-cloudy-tftpd"
    version: "1"
    depends:
    - tftpd-hpa

- name: Change blocks in tftpd configuration
  loop: '{{ tftpd_config|default([]) }}'
  when: "'blockinfile' in item"
  blockinfile: "{{ item['blockinfile'] }}"
  register: tftpd_config_blockinfile_result
  notify:
  - 'Restart tftpd service to apply changes'

- name: Copy files to tftpd configuration
  loop: '{{ tftpd_config|default([]) }}'
  when: "'copy' in item"
  copy: "{{ item['copy'] }}"
  register: tftpd_config_copy_result
  notify:
  - 'Restart tftpd service to apply changes'

- name: Change debconf selections for tftpd
  loop: '{{ tftpd_config|default([]) }}'
  when: "'debconf' in item"
  debconf: "{{ item['debconf'] }}"
  register: tftpd_config_debconf_result
  notify:
  - 'Restart tftpd service to apply changes'

- name: Manage files in tftpd configuration
  loop: '{{ tftpd_config|default([]) }}'
  when: "'file' in item"
  file: "{{ item['file'] }}"
  register: tftpd_config_file_result
  notify:
  - 'Restart tftpd service to apply changes'

- name: Change lines in tftpd configuration
  loop: '{{ tftpd_config|default([]) }}'
  when: "'lineinfile' in item"
  lineinfile: "{{ item['lineinfile'] }}"
  register: tftpd_config_lineinfile_result
  notify:
  - 'Restart tftpd service to apply changes'

- name: Generate tftpd configuration from templates
  loop: '{{ tftpd_config|default([]) }}'
  when: "'template' in item"
  template: "{{ item['template'] }}"
  register: tftpd_config_template_result
  notify:
  - 'Restart tftpd service to apply changes'

- name: Manage tftpd service
  service:
    enabled: '{{ tftpd_service_enabled }}'
    name: '{{ tftpd_service_name }}'
    state: '{{ tftpd_service_state }}'

- name: Debug role variables
  debug:
    msg:
      tftpd_config_blockinfile_result: '{{ tftpd_config_blockinfile_result }}'
      tftpd_config_copy_result: '{{ tftpd_config_copy_result }}'
      tftpd_config_debconf_result: '{{ tftpd_config_debconf_result }}'
      tftpd_config_file_result: '{{ tftpd_config_file_result }}'
      tftpd_config_lineinfile_result: '{{ tftpd_config_lineinfile_result }}'
      tftpd_config_template_result: '{{ tftpd_config_template_result }}'
  tags:
    - never
    - debug
