---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Detach floating ips
  loop: "{{ openstack_server_floating_ips|default([]) }}"
  openstack.cloud.floating_ip:
    auth: '{{ openstack_auth }}'
    cloud: '{{ openstack_cloud }}'
    floating_ip_address: '{{ item.floating_ip_address|default(omit) }}'
    interface: '{{ openstack_interface|default(omit) }}'
    purge: '{{ item.purge|default(omit) }}'
    server: '{{ openstack_server_name|mandatory }}'
    state: absent
    wait: yes
  register: openstack_floating_ip_result

- name: Delete compute instance
  openstack.cloud.server:
    auth: '{{ openstack_auth }}'
    cloud: '{{ openstack_cloud }}'
    delete_fip: '{{ openstack_server_delete_fip|default(omit) }}'
    interface: '{{ openstack_interface|default(omit) }}'
    name: '{{ openstack_server_name|mandatory }}'
    state: absent
  register: openstack_server_result

- name: Delete network ports
  loop: '{{ openstack_network_ports|default([]) }}'
  openstack.cloud.port:
    auth: '{{ openstack_auth }}'
    cloud: '{{ openstack_cloud }}'
    interface: '{{ openstack_interface|default(omit) }}'
    name: '{{ item.name|mandatory }}'
    state: absent
  when: item.network|default(None) != None # Only delete what might has been created

- name: Debug role variables
  debug:
    msg:
      openstack_server_result: '{{ openstack_server_result }}'
      openstack_floating_ip_result: '{{ openstack_floating_ip_result }}'
  tags:
    - never
    - debug
