---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: 'Apply Netplan configuration'
  ansible.builtin.command: # noqa no-changed-when
    cmd: 'netplan apply'
  notify:
  # To apply device name changes it might be required to reboot
  - "Reboot after Netplan configuration changes have been applied successfully"

- name: 'Reboot after Netplan configuration changes have been applied successfully'
  ansible.builtin.reboot:
