# NOTE: Keep this file in sync with configuration of Ansible Galaxy YamlLinter at
#       https://github.com/ansible/galaxy/blob/master/galaxy/importer/linters/yamllint.yaml
#       and ansible-lint's default yamllint configuration at
#       https://github.com/ansible/ansible-lint/blob/main/src/ansiblelint/data/.yamllint
---
# Based on ansible-lint config
extends: default

rules:
  # Ref.: https://github.com/ansible/galaxy/blob/master/galaxy/importer/linters/yamllint.yaml
  #braces: {max-spaces-inside: 1, level: error}
  brackets: {max-spaces-inside: 1, level: error}
  colons: {max-spaces-after: -1, level: error}
  commas: {max-spaces-after: -1, level: error}
  #comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines: {max: 3, level: error}
  hyphens: {level: error}
  indentation: disable
  key-duplicates: enable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines: {type: unix}
  trailing-spaces: disable
  truthy: disable

  # Ref.: https://github.com/ansible/ansible-lint/blob/main/src/ansiblelint/data/.yamllint
  comments:
    # https://github.com/prettier/prettier/issues/6780
    min-spaces-from-content: 1
  # https://github.com/adrienverge/yamllint/issues/384
  #comments-indentation: false
  #document-start: disable
  # 160 chars was the default used by old E204 rule, but
  # you can easily change it or disable in your .yamllint file.
  #line-length:
  #  max: 160
  # We are adding an extra space inside braces as that's how prettier does it
  # and we are trying not to fight other linters.
  braces:
    min-spaces-inside: 0 # yamllint defaults to 0
    max-spaces-inside: 1 # yamllint defaults to 0
  # key-duplicates:
  #   forbid-duplicated-merge-keys: true # not enabled by default
  octal-values:
    forbid-implicit-octal: true # yamllint defaults to false
    forbid-explicit-octal: true # yamllint defaults to false
  # quoted-strings:
  #   quote-type: double
  #   required: only-when-needed
