---
authors:
  - Jakob Meng (https://github.com/jm1)
dependencies:
  "ansible.posix": '>=1.3.0'
  "ansible.utils": '>=2.5.2'
  "community.general": '>=3.5.0'
  "community.libvirt": '>=1.0.2'
  "jm1.ansible": '>=2022.10.23'
  "jm1.libvirt": '>=2022.2.1'
  "jm1.packages": '>=2022.2.1'
  "jm1.pkg": '>=2022.2.1'
  "jm1.openstack": '>=2022.10.27'
  "openstack.cloud": '>=1.5.0'
description: null
documentation: https://github.com/jm1/ansible-collection-jm1-cloudy/tree/master/docs
homepage: https://github.com/jm1/ansible-collection-jm1-cloudy
issues: https://github.com/jm1/ansible-collection-jm1-cloudy/issues
#license: GPL-3.0-or-later
license_file: LICENSE.md
name: cloudy
namespace: jm1
readme: README.md
repository: https://github.com/jm1/ansible-collection-jm1-cloudy
tags: null
version: 2022.2.1
