---
authors:
  - Jakob Meng (https://github.com/jm1)
dependencies:
  "ansible.posix": '>=1.3.0'
  "ansible.utils": '>=2.5.2'
  "community.crypto": '>=1.0.0'
  "community.general": '>=3.5.0'
  "community.libvirt": '>=1.0.2'
  "jm1.ansible": '>=2025.11.26'
  "jm1.libvirt": '>=2024.5.30'
  "jm1.openstack": '>=2024.5.30'
  "jm1.packages": '>=2024.5.30'
  "jm1.pkg": '>=2024.5.30'
  "kubernetes.core": '>=2.4.0'
  "openstack.cloud": '>=1.5.0'
description: null
documentation: https://github.com/jm1/ansible-collection-jm1-cloudy/tree/master/docs
homepage: https://github.com/jm1/ansible-collection-jm1-cloudy
issues: https://github.com/jm1/ansible-collection-jm1-cloudy/issues
#license: GPL-3.0-or-later
license_file: LICENSE.md
name: cloudy
namespace: jm1
readme: README.md
repository: https://github.com/jm1/ansible-collection-jm1-cloudy
tags: null
version: 2025.12.19
