---
roles:
- jm1.common
- jm1.kvm_nested_virtualization
- jm1.tftpd

collections:
- ansible.netcommon
- ansible.posix
- community.general
- community.libvirt
- jm1.libvirt
- jm1.packages
- jm1.pkg
- jm1.openstack
- openstack.cloud
