---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Fail if required vars are not set
  fail:
  when: >
    openstack_server_name == None or openstack_server_name|length == 0

- name: Fetch server info
  openstack.cloud.server_info:
    auth: '{{ openstack_auth }}'
    cloud: '{{ openstack_cloud }}'
    filters:
      name: '{{ openstack_server_name|mandatory }}'
    interface: '{{ openstack_interface|default(omit) }}'
  register: openstack_server_info_result

- name: Enforce unique server names
  assert:
    that:
      openstack_server_info_result.openstack_servers|length < 2
    fail_msg: >-
        Found several servers sharing the same name:
        {{ openstack_server_info_result.openstack_servers|map(attribute='name')|join(' ') }}

- name: Prepare server info
  set_fact:
    openstack_server_info: '{{ openstack_server_info_result.openstack_servers[0] }}'
  when: openstack_server_info_result.openstack_servers|length > 0

- name: Nullify server info
  set_fact:
    openstack_server_info: !!null
  when: openstack_server_info_result.openstack_servers|length == 0

- name: Cleanup temporary results
  set_fact:
    openstack_server_info_result: !!null

- name: Debug role variables
  debug:
    msg:
      openstack_server_info: '{{ openstack_server_info }}'
  tags:
    - never
    - debug
