---
# Copyright (c) 2021-2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Verify task definitions specified in dhcpd_config variable
  when: item is not mapping or (item.keys() | difference(['register', 'when'])) | list | length != 1
  ansible.builtin.fail:
    msg: >-
      Unsupported keyword or multiple module definitions found:
      {{ (item.keys() | difference(['register', 'when'])) | join(', ') }}.
  loop: '{{ dhcpd_config | default([]) }}'

- name: Verify task definitions specified in dhcpd6_config variable
  when: item is not mapping or (item.keys() | difference(['register', 'when'])) | list | length != 1
  ansible.builtin.fail:
    msg: >-
      Unsupported keyword or multiple module definitions found:
      {{ (item.keys() | difference(['register', 'when'])) | join(', ') }}.
  loop: '{{ dhcpd6_config | default([]) }}'

- name: Install dependencies of collection jm1.pkg
  ansible.builtin.import_role:
    name: jm1.pkg.setup # If Ansible raises "ERROR! the role 'jm1.pkg.setup' was not found" then you might use the
                        # ansible-galaxy and the provided requirements.yml to install all missing role dependencies.

# No need to update apt cache here because role jm1.pkg.setup handles apt cache updates already
- name: Satisfy requirements on Debian and Ubuntu
  when: distribution_id | first in ['Debian', 'Ubuntu']
  jm1.pkg.meta_pkg:
    name: "jm1-cloudy-dhcpd"
    version: "1"
    depends:
    - isc-dhcp-server

- name: Satisfy requirements on Red Hat Enterprise Linux 7 and CentOS 7
  when: distribution_id | first in ['CentOS', 'Red Hat Enterprise Linux'] and distribution_id | last == '7'
  jm1.pkg.meta_pkg:
    name: "jm1-cloudy-dhcpd"
    version: "1"
    depends:
    - dhcp

- name: Satisfy requirements on Red Hat Enterprise Linux 8 and 9 and CentOS 8 and 9
  when: distribution_id | first in ['CentOS', 'Red Hat Enterprise Linux'] and distribution_id | last in ['8', '9']
  jm1.pkg.meta_pkg:
    name: "jm1-cloudy-dhcpd"
    version: "1"
    depends:
    - dhcp-server

# "If you are here to restrict what interfaces should dhcpd listen on,
#  be aware that dhcpd listens *only* on interfaces for which it finds subnet
#  declaration in dhcpd.conf. It means that explicitly enumerating interfaces
#  also on command line should not be required in most cases."
# Ref.: /etc/sysconfig/dhcpd on Red Hat Enterprise Linux or CentOS

- name: Run tasks specified in dhcpd_config variable
  jm1.ansible.execute_module:
    name: "{{ (item.keys() | difference(['register', 'when'])) | first }}"
    args: "{{ item[(item.keys() | difference(['register', 'when'])) | first] }}"
    register: "{{ item['register'] | default(omit) }}"
    when: item['when'] | default(omit)
  loop: "{{ dhcpd_config | default([]) }}"
  notify:
  - 'Restart DHCP IPv4 service to apply changes'

- name: Run tasks specified in dhcpd6_config variable
  jm1.ansible.execute_module:
    name: "{{ (item.keys() | difference(['register', 'when'])) | first }}"
    args: "{{ item[(item.keys() | difference(['register', 'when'])) | first] }}"
    register: "{{ item['register'] | default(omit) }}"
    when: item['when'] | default(omit)
  loop: "{{ dhcpd6_config | default([]) }}"
  notify:
  - 'Restart DHCP IPv6 service to apply changes'

# Debian provides a single service for DHCP IPv4 and DHCP IPv6 only
# CentOS, Red Hat Enterprise Linux and Ubuntu provide different services for DHCP IPv4 and DHCP IPv6

- name: Manage DHCP IPv4 (and DHCP IPv6) service
  ansible.builtin.service:
    name: '{{ dhcpd_service_name }}'
    state: '{{ dhcpd_service_state }}'
    enabled: '{{ dhcpd_service_enabled }}'

- name: Manage DHCP IPv6 service
  when: distribution_id | first != 'Debian'
  ansible.builtin.service:
    name: '{{ dhcpd6_service_name }}'
    state: '{{ dhcpd6_service_state }}'
    enabled: '{{ dhcpd6_service_enabled }}'
