---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Install dependencies of collection jm1.pkg
  import_role:
    name: jm1.pkg.setup # If Ansible raises "ERROR! the role 'jm1.pkg.setup' was not found" then you might use the
                        # ansible-galaxy and the provided requirements.yml to install all missing role dependencies.

# No need to update apt cache here because role jm1.pkg.setup handles apt cache updates already
- name: Satisfy requirements on Debian and Ubuntu
  when: distribution_id|first in ['Debian', 'Ubuntu']
  jm1.pkg.meta_pkg:
    name: "jm1-cloudy-dhcpd"
    version: "1"
    depends:
    - isc-dhcp-server

- name: Satisfy requirements on Red Hat Enterprise Linux 7 and CentOS 7
  when: distribution_id|first in ['CentOS', 'Red Hat Enterprise Linux'] and distribution_id|last == '7'
  jm1.pkg.meta_pkg:
    name: "jm1-cloudy-dhcpd"
    version: "1"
    depends:
    - dhcp

- name: Satisfy requirements on Red Hat Enterprise Linux 8 and CentOS 8
  when: distribution_id|first in ['CentOS', 'Red Hat Enterprise Linux'] and distribution_id|last == '8'
  jm1.pkg.meta_pkg:
    name: "jm1-cloudy-dhcpd"
    version: "1"
    depends:
    - dhcp-server

# "If you are here to restrict what interfaces should dhcpd listen on,
#  be aware that dhcpd listens *only* on interfaces for which it finds subnet
#  declaration in dhcpd.conf. It means that explicitly enumerating interfaces
#  also on command line should not be required in most cases."
# Ref.: /etc/sysconfig/dhcpd on Red Hat Enterprise Linux or CentOS

- name: Change blocks in dhcpd configuration
  loop: '{{ dhcpd_config|default([]) }}'
  when: "'blockinfile' in item"
  blockinfile: "{{ item['blockinfile'] }}"
  register: dhcpd_config_blockinfile_result
  notify:
  - 'Restart DHCP IPv4 service to apply changes'

- name: Copy files to dhcpd configuration
  loop: '{{ dhcpd_config|default([]) }}'
  when: "'copy' in item"
  copy: "{{ item['copy'] }}"
  register: dhcpd_config_copy_result
  notify:
  - 'Restart DHCP IPv4 service to apply changes'

- name: Change debconf selections for dhcpd
  loop: '{{ dhcpd_config|default([]) }}'
  when: "'debconf' in item"
  debconf: "{{ item['debconf'] }}"
  register: dhcpd_config_debconf_result
  notify:
  - 'Restart DHCP IPv4 service to apply changes'

- name: Manage files in dhcpd configuration
  loop: '{{ dhcpd_config|default([]) }}'
  when: "'file' in item"
  file: "{{ item['file'] }}"
  register: dhcpd_config_file_result
  notify:
  - 'Restart DHCP IPv4 service to apply changes'

- name: Change lines in dhcpd configuration
  loop: '{{ dhcpd_config|default([]) }}'
  when: "'lineinfile' in item"
  lineinfile: "{{ item['lineinfile'] }}"
  register: dhcpd_config_lineinfile_result
  notify:
  - 'Restart DHCP IPv4 service to apply changes'

- name: Generate dhcpd configuration from templates
  loop: '{{ dhcpd_config|default([]) }}'
  when: "'template' in item"
  template: "{{ item['template'] }}"
  register: dhcpd_config_template_result
  notify:
  - 'Restart DHCP IPv4 service to apply changes'

- name: Change blocks in dhcpd6 configuration
  loop: '{{ dhcpd6_config|default([]) }}'
  when: "'blockinfile' in item"
  blockinfile: "{{ item['blockinfile'] }}"
  register: dhcpd6_config_blockinfile_result
  notify:
  - 'Restart DHCP IPv6 service to apply changes'

- name: Copy files to dhcpd6 configuration
  loop: '{{ dhcpd6_config|default([]) }}'
  when: "'copy' in item"
  copy: "{{ item['copy'] }}"
  register: dhcpd6_config_copy_result
  notify:
  - 'Restart DHCP IPv6 service to apply changes'

- name: Change debconf selections for dhcpd6
  loop: '{{ dhcpd6_config|default([]) }}'
  when: "'debconf' in item"
  debconf: "{{ item['debconf'] }}"
  register: dhcpd6_config_debconf_result
  notify:
  - 'Restart DHCP IPv6 service to apply changes'

- name: Manage files in dhcpd6 configuration
  loop: '{{ dhcpd6_config|default([]) }}'
  when: "'file' in item"
  file: "{{ item['file'] }}"
  register: dhcpd6_config_file_result
  notify:
  - 'Restart DHCP IPv6 service to apply changes'

- name: Change lines in dhcpd6 configuration
  loop: '{{ dhcpd6_config|default([]) }}'
  when: "'lineinfile' in item"
  lineinfile: "{{ item['lineinfile'] }}"
  register: dhcpd6_config_lineinfile_result
  notify:
  - 'Restart DHCP IPv6 service to apply changes'

- name: Generate dhcpd6 configuration from templates
  loop: '{{ dhcpd6_config|default([]) }}'
  when: "'template' in item"
  template: "{{ item['template'] }}"
  register: dhcpd6_config_template_result
  notify:
  - 'Restart DHCP IPv6 service to apply changes'

# Debian provides a single service for DHCP IPv4 and DHCP IPv6 only
# CentOS, Red Hat Enterprise Linux and Ubuntu provide different services for DHCP IPv4 and DHCP IPv6

- name: Manage DHCP IPv4 (and DHCP IPv6) service
  service:
    name: '{{ dhcpd_service_name }}'
    state: '{{ dhcpd_service_state }}'
    enabled: '{{ dhcpd_service_enabled }}'

- name: Manage DHCP IPv6 service
  when: distribution_id|first != 'Debian'
  service:
    name: '{{ dhcpd6_service_name }}'
    state: '{{ dhcpd6_service_state }}'
    enabled: '{{ dhcpd6_service_enabled }}'

- name: Debug role variables
  debug:
    msg:
      dhcpd_config_blockinfile_result: '{{ dhcpd_config_blockinfile_result }}'
      dhcpd_config_copy_result: '{{ dhcpd_config_copy_result }}'
      dhcpd_config_debconf_result: '{{ dhcpd_config_debconf_result }}'
      dhcpd_config_file_result: '{{ dhcpd_config_file_result }}'
      dhcpd_config_lineinfile_result: '{{ dhcpd_config_lineinfile_result }}'
      dhcpd_config_template_result: '{{ dhcpd_config_template_result }}'
      dhcpd6_config_blockinfile_result: '{{ dhcpd6_config_blockinfile_result }}'
      dhcpd6_config_copy_result: '{{ dhcpd6_config_copy_result }}'
      dhcpd6_config_debconf_result: '{{ dhcpd6_config_debconf_result }}'
      dhcpd6_config_file_result: '{{ dhcpd6_config_file_result }}'
      dhcpd6_config_lineinfile_result: '{{ dhcpd6_config_lineinfile_result }}'
      dhcpd6_config_template_result: '{{ dhcpd6_config_template_result }}'
  tags:
    - never
    - debug
