---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: 'Restart sshd service to apply changes'
  when: sshd_service_state != 'stopped'
  ansible.builtin.service:
    name: '{{ sshd_service_name }}'
    state: restarted
