---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Add/Modify/Delete SSH authorized keys
  loop: "{{ ssh_authorized_keys|default([]) }}"
  authorized_key: '{{ item }}'
  register: authorized_key_result

- name: Debug role variables
  debug:
    msg:
      authorized_key_result: '{{ authorized_key_result }}'
  tags:
    - never
    - debug
