---
# Copyright (c) 2020-2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Add/Modify/Delete SSH authorized keys
  loop: "{{ ssh_authorized_keys | default([]) }}"
  ansible.posix.authorized_key: '{{ item }}' # noqa args[module]
