---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Add/Modify/Delete SSH authorized keys
  loop: "{{ ssh_authorized_keys|default([]) }}"
  authorized_key: '{{ item }}'
    #comment: '{{ item.comment|default(omit) }}'
    #exclusive: '{{ item.exclusive|default(omit) }}'
    #follow: '{{ item.follow|default(omit) }}'
    #key: '{{ item.key|mandatory }}'
    #key_options: '{{ item.key_options|default(omit) }}'
    #manage_dir: '{{ item.manage_dir|default(omit) }}'
    #path: '{{ item.path|default(omit) }}'
    #state: '{{ item.state|default(omit) }}'
    #user: '{{ item.user|default(ansible_user) }}'
    #validate_certs: '{{ item.validate_certs|default(omit) }}'
  register: authorized_key_result

- name: Debug role variables
  debug:
    msg:
      authorized_key_result: '{{ authorized_key_result }}'
  tags:
    - never
    - debug
