---
# Copyright (c) 2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

distribution_id:
- 'Ubuntu'
- '22.04'

libvirt_domain_autostart: no

libvirt_host_become: no

libvirt_netplan:
  ethernets:
    eth0:
      dhcp4: false
      dhcp6: false
      accept-ra: false

      addresses:
      - 192.168.156.23/24

      nameservers:
        addresses:
        - 192.168.156.1
      routes:
      - to: 0.0.0.0/0
        via: 192.168.156.1

libvirt_pool: 'default'

libvirt_uri: 'qemu:///session'

libvirt_volumes:
- backing_vol: 'ubuntu-22.04-server-cloudimg-amd64.img'
  backing_vol_format: 'qcow2'
  capacity: 5G
  format: 'qcow2'
  linked: no
  name: '{{ fqdn }}.qcow2'
  pool: '{{ libvirt_pool }}'
  prealloc_metadata: no
  state: present
