---
# Copyright (c) 2023 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

distribution_id:
- 'Ubuntu'
- '22.04'

libvirt_domain_autostart: false

libvirt_host_become: false

libvirt_netplan:
  ethernets:
    eth0:
      dhcp4: false
      dhcp6: false
      accept-ra: false

      addresses:
      - 192.168.158.24/24

      nameservers:
        addresses:
        - 192.168.158.1
      routes:
      - to: 0.0.0.0/0
        via: 192.168.158.1

libvirt_pool: 'default'

libvirt_uri: 'qemu:///session'

libvirt_volumes:
- backing_vol: 'ubuntu-22.04-server-cloudimg-amd64.img'
  backing_vol_format: 'qcow2'
  capacity: 10G
  format: 'qcow2'
  linked: false
  name: '{{ fqdn }}.qcow2'
  pool: '{{ libvirt_pool }}'
  prealloc_metadata: false
  state: present

podman_config:
- # Create systemd service unit for running Apache HTTP server in a Podman container
  become: true
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Apache HTTP server in a Podman container
      Wants=network.target
      After=network-online.target

      [Service]
      Environment=PODMAN_SYSTEMD_UNIT=%n
      Restart=on-failure
      TimeoutStopSec=70
      ExecStartPre=/bin/rm -f %t/podman-httpd.pid %t/podman-httpd.ctr-id
      ExecStart=/usr/bin/podman run \
        --conmon-pidfile %t/podman-httpd.pid \
        --cidfile %t/podman-httpd.ctr-id \
        --cgroups=no-conmon \
        --replace \
        --detach --tty --publish 8080:80/tcp --name httpd docker.io/library/httpd
      ExecStop=/usr/bin/podman stop --ignore --cidfile %t/podman-httpd.ctr-id -t 10
      ExecStopPost=/usr/bin/podman rm --ignore -f --cidfile %t/podman-httpd.ctr-id
      PIDFile=%t/podman-httpd.pid
      Type=forking

      [Install]
      WantedBy=multi-user.target default.target
    dest: /etc/systemd/system/podman-httpd.service
  handlers:
  - # On changes reload systemd daemon and restart Podman container
    become: true
    ansible.builtin.service:
      daemon_reload: true
      name: podman-httpd.service
      state: restarted
- # Ensure systemd service is enabled
  become: true
  ansible.builtin.service:
    enabled: true
    name: podman-httpd.service
- # Force changes to be applied now
  ansible.builtin.meta: flush_handlers
