---
# Copyright (c) 2020-2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

debconf_early_config:
- name: 'apt-cacher-ng'
  question: 'apt-cacher-ng/bindaddress'
  value: '127.0.0.1 ::1'
  vtype: 'string'
- name: 'apt-cacher-ng'
  question: 'apt-cacher-ng/tunnelenable'
  value: 'false'
  vtype: 'boolean'

dhcpd_config:
- ansible.builtin.copy:
    content: |
      # 2021-2022 Jakob Meng, <jakobmeng@web.de>
      #
      # Configuration file for ISC dhcpd
      #
      # NOTE: On Ubuntu, if /etc/ltsp/dhcpd.conf exists, that will be used as configuration file instead of this file.

      # option definitions common to all supported networks...
      option domain-name "{{ dns_suffix }}";
      option domain-name-servers 192.168.158.1;
      option space pxelinux;
      option pxelinux.magic code 208 = string;
      option pxelinux.configfile code 209 = text;
      option pxelinux.pathprefix code 210 = text;
      option pxelinux.reboottime code 211 = unsigned integer 32;
      option architecture-type code 93 = unsigned integer 16;

      default-lease-time 600;
      max-lease-time 7200;

      # The ddns-updates-style parameter controls whether or not the server will
      # attempt to do a DNS update when a lease is confirmed. We default to the
      # behavior of the version 2 packages ('none', since DHCP v2 didn't
      # have support for DDNS.)
      ddns-update-style none;

      # If this DHCP server is the official DHCP server for the local
      # network, the authoritative directive should be uncommented.
      authoritative;

      # Use this to send dhcp log messages to a different log file (you also
      # have to hack syslog.conf to complete the redirection).
      log-facility local7;

      subnet 192.168.153.0 netmask 255.255.255.0 {
        option routers 192.168.153.2;
        range 192.168.153.10 192.168.153.254;
      } # subnet 192.168.153.0 netmask 255.255.255.0

      {% for pxe_client in pxe_installer_clients %}
      host {{ hostvars[pxe_client].inventory_hostname }} {
        next-server {{ pxe_installer_host_address }};
        option host-name "{{ hostvars[pxe_client].inventory_hostname }}";
        {{ hostvars[pxe_client].dhcpd_host_config | indent(width=2) }}

        if option architecture-type = 00:07 {
          filename "{{ pxe_installer_distribution_filename_map
                       [hostvars[pxe_client]['distribution_id'] | join('_') | regex_replace('[^A-Za-z0-9_]', '_')]
                       [hostvars[pxe_client]['os_architecture']]['UEFI'] }}";
        } else {
          filename "{{ pxe_installer_distribution_filename_map
                       [hostvars[pxe_client]['distribution_id'] | join('_') | regex_replace('[^A-Za-z0-9_]', '_')]
                       [hostvars[pxe_client]['os_architecture']]['BIOS'] }}";
        }
      } # host {{ hostvars[pxe_client].inventory_hostname }}
      {% endfor %}

    dest: /etc/dhcp/dhcpd.conf
    group: root
    mode: u=rw,g=r,o=
    owner: root
- # Configure IPv4 interfaces that DHCP IPv4 service will listen to
  ansible.builtin.lineinfile:
    path: /etc/default/isc-dhcp-server
    regexp: "^INTERFACESv4=.*"
    line: 'INTERFACESv4="eth1"'
- # Remove IPv6 interfaces to disable DHCP IPv6 service
  ansible.builtin.lineinfile:
    path: /etc/default/isc-dhcp-server
    regexp: "^INTERFACESv6=.*"
    line: 'INTERFACESv6=""'

dhcpd6_service_enabled: false

dhcpd6_service_state: 'stopped'

distribution_id:
- 'Debian'
- '11'

httpd_config:
- ansible.builtin.file:
    path: /var/www/html
    state: absent
- ansible.builtin.file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
- ansible.builtin.copy:
    content: |
      # 2021 Jakob Meng, <jakobmeng@web.de>

      <VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www

        <Directory /var/www>
          Options -Indexes
          Require ip 192.168.153
          Require ip 192.168.158.20
          Require ip 127.
          Require ip ::1
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
      </VirtualHost>
    dest: /etc/apache2/sites-available/cloud-init.conf
- ansible.builtin.file:
    src: /etc/apache2/sites-available/cloud-init.conf
    dest: /etc/apache2/sites-enabled/cloud-init.conf
    state: link
- community.general.apache2_module:
    state: present
    name: proxy
- community.general.apache2_module:
    state: present
    name: proxy_http
- community.general.apache2_module:
    state: present
    name: proxy_http2
- community.general.apache2_module:
    state: present
    name: proxy_connect
- community.general.apache2_module:
    state: present
    name: cache
- community.general.apache2_module:
    state: present
    name: cache_disk
- community.general.apache2_module:
    state: present
    name: expires
- community.general.apache2_module:
    state: present
    name: headers
- community.general.apache2_module:
    state: present
    name: ssl
- ansible.builtin.copy:
    content: |
      # 2021 Jakob Meng, <jakobmeng@web.de>

      Listen 8080

      <VirtualHost *:8080>
        ProxyRequests On
        ProxyVia On
        <Proxy "*">
          Require ip 192.168.153
          Require ip 192.168.158.20
          Require ip 127.
          Require ip ::1
        </Proxy>

        # Redirect to apt-cacher-ng
        ProxyRemote http://archive.ubuntu.com http://127.0.0.1:3142/
        ProxyRemote http://de.archive.ubuntu.com http://127.0.0.1:3142/
        ProxyRemote http://deb.debian.org http://127.0.0.1:3142/

        CacheRoot /var/cache/apache2/mod_cache_disk
        CacheQuickHandler off
        CacheIgnoreHeaders Set-Cookie
        CacheLock on
        # CacheLockMaxAge must be long enough to download files else caching wont work
        CacheLockMaxAge 3600
        CacheDetailHeader on
        CacheHeader on
        CacheDefaultExpire 86400
        CacheMinFileSize 0
        CacheMaxFileSize 16000000000
        # Caching only works with http, not https
        CacheEnable disk "http://*releases.ubuntu.com"

        SSLProxyEngine off

        # Use local reverse proxies to work around the limitation that caching is only possible with http but not https
        ProxyRemote       "http://releases.ubuntu.com/"      "http://127.0.0.1:8081"
        ProxyRemote       "http://old-releases.ubuntu.com/"  "http://127.0.0.1:8082"

        ExpiresActive on
        ExpiresDefault "access plus 30 days"

        Header merge Cache-Control public
        FileETag All

        ErrorLog ${APACHE_LOG_DIR}/error_forward_proxy.log
        CustomLog ${APACHE_LOG_DIR}/access_forward_proxy.log combined
      </VirtualHost>
    dest: /etc/apache2/sites-available/forward-proxy.conf
- ansible.builtin.file:
    src: /etc/apache2/sites-available/forward-proxy.conf
    dest: /etc/apache2/sites-enabled/forward-proxy.conf
    state: link
- ansible.builtin.copy:
    content: |
      # 2021 Jakob Meng, <jakobmeng@web.de>

      # Forward http requests via https to releases.ubuntu.com
      Listen 8081
      <VirtualHost *:8081>
        ProxyRequests Off
        SSLProxyEngine on
        ProxyPass         "/"     "https://releases.ubuntu.com/"
        ProxyPassReverse  "/"     "https://releases.ubuntu.com/"
        ErrorLog ${APACHE_LOG_DIR}/error_reverse_proxy.log
        CustomLog ${APACHE_LOG_DIR}/access_reverse_proxy.log combined
      </VirtualHost>

      # Forward http requests via https to old-releases.ubuntu.com
      Listen 8082
      <VirtualHost *:8082>
        ProxyRequests Off
        SSLProxyEngine on
        ProxyPass         "/" "https://old-releases.ubuntu.com/"
        ProxyPassReverse  "/" "https://old-releases.ubuntu.com/"
        ErrorLog ${APACHE_LOG_DIR}/error_reverse_proxy.log
        CustomLog ${APACHE_LOG_DIR}/access_reverse_proxy.log combined
      </VirtualHost>
    dest: /etc/apache2/sites-available/reverse-proxy.conf
- ansible.builtin.file:
    src: /etc/apache2/sites-available/reverse-proxy.conf
    dest: /etc/apache2/sites-enabled/reverse-proxy.conf
    state: link

iptables_config:
- # do SNAT for all packets coming from internal router network
  ansible.builtin.iptables:
    chain: POSTROUTING
    destination: 0.0.0.0/0
    jump: SNAT
    out_interface: 'eth0'
    source: 192.168.153.0/24
    table: nat
    to_source: 192.168.158.20

iptables_persistence: true

libvirt_domain_autostart: false

libvirt_hardware:
- cpu: 'host-passthrough,cache.mode=passthrough'
- vcpus: '4'
- memory: '4096'
- virt_type: 'kvm'
- graphics: 'vnc,listen=socket'
- network: 'network=route-1-no-dhcp,model=virtio'
- network: 'network=isolated-2-no-dhcp,model=virtio'
- disk: "vol='{{ libvirt_pool }}/{{ libvirt_volumes[0]['name'] }}',device=disk,bus=virtio"
- disk: "vol='{{ libvirt_pool }}/{{ libvirt_configdrive }}',device=disk,bus=virtio,serial='cidata'"
- os_variant: 'debian10'

libvirt_host_become: false

libvirt_netplan:
  ethernets:
    eth0:
      dhcp4: false
      dhcp6: false
      accept-ra: false

      addresses:
      - 192.168.158.20/24

      nameservers:
        addresses:
        - 192.168.158.1
      routes:
      - to: 0.0.0.0/0
        via: 192.168.158.1
    eth1:
      dhcp4: false
      dhcp6: false
      accept-ra: false

      addresses:
      - 192.168.153.2/24

libvirt_pool: 'default'

libvirt_uri: 'qemu:///session'

libvirt_volumes:
- backing_vol: 'debian-11-genericcloud-amd64.qcow2'
  backing_vol_format: 'qcow2'
  capacity: 64G
  format: 'qcow2'
  linked: false
  name: '{{ fqdn }}.qcow2'
  pool: '{{ libvirt_pool }}'
  prealloc_metadata: false
  state: present

meta_packages:
- name: jm1-system-tools
  depends:
  - iptables-persistent # Used to (re)store iptables SNAT rules
  - apt-cacher-ng
  version: 2

pxe_installer_clients:
- lvrt-lcl-session-srv-110-pxe-client-debian11-bios
- lvrt-lcl-session-srv-111-pxe-client-debian11-uefi
- lvrt-lcl-session-srv-112-pxe-client-debian12-bios
- lvrt-lcl-session-srv-113-pxe-client-debian12-uefi
- lvrt-lcl-session-srv-120-pxe-client-ubuntu2004-bios
- lvrt-lcl-session-srv-121-pxe-client-ubuntu2004-uefi
- lvrt-lcl-session-srv-122-pxe-client-ubuntu2204-bios
- lvrt-lcl-session-srv-123-pxe-client-ubuntu2204-uefi
- lvrt-lcl-session-srv-130-pxe-client-centos8-bios
- lvrt-lcl-session-srv-131-pxe-client-centos8-uefi
- lvrt-lcl-session-srv-132-pxe-client-centos9-bios
- lvrt-lcl-session-srv-133-pxe-client-centos9-uefi

pxe_installer_host_address: 192.168.153.2

# NOTE: Unencrypted http connections are used here because caching is not possible with encrypted https connections.
#       A proxy is used to transparently upgrade http connections to https connections!
pxe_installer_files_ubuntu_1804_amd64:
  efi: 'http://archive.ubuntu.com/ubuntu/dists/bionic/main/uefi/grub2-amd64/current/grubnetx64.efi.signed'
  iso: 'http://releases.ubuntu.com/bionic/ubuntu-18.04.6-live-server-amd64.iso'
  pxe: 'http://archive.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/current/images/netboot/netboot.tar.gz'

pxe_installer_files_ubuntu_2004_amd64:
  efi: 'http://archive.ubuntu.com/ubuntu/dists/focal/main/uefi/grub2-amd64/current/grubnetx64.efi.signed'
  iso: 'http://releases.ubuntu.com/focal/ubuntu-20.04.6-live-server-amd64.iso'
  pxe: 'http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/netboot.tar.gz'

pxe_installer_files_ubuntu_2204_amd64:
  efi: 'http://archive.ubuntu.com/ubuntu/dists/jammy/main/uefi/grub2-amd64/current/grubnetx64.efi.signed'
  iso: 'http://releases.ubuntu.com/jammy/ubuntu-22.04.3-live-server-amd64.iso'
  pxe: 'http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/netboot.tar.gz'

sysctl_config:
- ansible.builtin.copy:
    content: |
      # 2021-2022 Jakob Meng, <jakobmeng@web.de>
      net.ipv4.ip_forward = 0
      net.ipv4.conf.eth0.forwarding = 1
      net.ipv4.conf.eth1.forwarding = 1
    dest: /etc/sysctl.d/10-ip-forward.conf
# Apply changes using Ansible's sysctl module
- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '0'
    state: present
    sysctl_file: /etc/sysctl.d/10-ip-forward.conf
    sysctl_set: true
- ansible.posix.sysctl:
    name: net.ipv4.conf.eth0.forwarding
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.d/10-ip-forward.conf
    sysctl_set: true
- ansible.posix.sysctl:
    name: net.ipv4.conf.eth1.forwarding
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.d/10-ip-forward.conf
    sysctl_set: true
