---
# Copyright (c) 2020 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

distribution_id:
- 'CentOS'
- '7'

libvirt_domain_autostart: false

libvirt_host_become: false

libvirt_netplan:
  ethernets:
    eth0:
      # When dhcp4 is set here then cloud-init on CentOS Linux 7 will set BOOTPROTO=dhcp instead of BOOTPROTO=none in
      # /etc/sysconfig/network-scripts/ifcfg-eth0 so static ip addresses are ignored. To workaround this bug, the dhcp4
      # setting is not defined here which causes cloud-init to use BOOTPROTO=none.
      #dhcp4: false

      # When dhcp4 is set here then cloud-init on CentOS Linux 7 will set IPV6INIT=true and DHCPV6C=true in
      # /etc/sysconfig/network-scripts/ifcfg-eth0 which will cause long boot delays while system is waiting on the
      # network. To workaround this bug, the dhcp6 setting is not defined here.
      #dhcp6: false
      accept-ra: false

      addresses:
      - 192.168.158.11/24

      nameservers:
        addresses:
        - 192.168.158.1
      routes:
      - to: 0.0.0.0/0
        via: 192.168.158.1

libvirt_pool: 'default'

libvirt_uri: 'qemu:///session'

libvirt_volumes:
- backing_vol: 'CentOS-7-x86_64-GenericCloud-2003.qcow2'
  backing_vol_format: 'qcow2'
  capacity: 10G
  format: 'qcow2'
  linked: false
  name: '{{ fqdn }}.qcow2'
  pool: '{{ libvirt_pool }}'
  prealloc_metadata: false
  state: present
