---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# Ansible controller is not supposed to connect to this host as it is used to debug pxe boot only
ansible_host: !!null

cloudinit_userdata: !!null # disable cloud-init userdata to prevent Jinja2 template errors due to undefined variables

libvirt_configdrive: !!null # disable cloud-init config drive

libvirt_domain_autostart: no

libvirt_domain_state: shutoff

libvirt_hardware:
- cpu: 'host'
- vcpus: '2'
- memory: '1024'
- virt_type: 'kvm'
- graphics: 'vnc,listen=socket'
- network: 'network=isolated-3-no-dhcp,model=virtio'
- disk: "vol='{{ libvirt_pool }}/{{ libvirt_volumes[0]['name'] }}',device=disk,bus=virtio"
- boot: 'hd,network'
- os_variant: 'debian10'

libvirt_host_become: no

libvirt_pool: 'default'

libvirt_uri: 'qemu:///session'

libvirt_volumes:
- capacity: 1G
  format: 'qcow2'
  name: '{{ fqdn }}.qcow2'
  pool: '{{ libvirt_pool }}'
  prealloc_metadata: no
  state: present

os_architecture: x86_64
