---
# Copyright (c) 2023 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

ansible_host: 192.168.158.82

chrony_config:
- ansible.builtin.copy:
    content: |
      # 2023 Jakob Meng, <jakobmeng@web.de>
      server 192.168.158.78 iburst
    dest: /etc/chrony/sources.d/home.arpa.sources
    mode: u=rw,g=r,o=r
    group: root
    owner: root

distribution_id:
- 'Ubuntu'
- '22.04'

# Kolla Ansible, in particular RabbitMQ, expects a hostname to resolve to a unique ip address,
# not both 127.0.0.1 and an ip address assigned by DHCP at the same time.
files_config_early: []

libvirt_domain_autostart: false

libvirt_hardware:
- cpu: 'host-passthrough,cache.mode=passthrough'
- vcpus: '4'
- memory: '8192'
- virt_type: 'kvm'
- graphics: 'vnc,listen=socket'
- network: 'network=route-1-no-dhcp,model=virtio,mac=52:54:00:aa:bb:2c'
- network: 'network=route-0-dhcp,model=virtio,mac=52:54:00:aa:bb:32'
- disk: "vol='{{ libvirt_pool }}/{{ libvirt_volumes[0]['name'] }}',device=disk,bus=virtio"
- disk: "vol='{{ libvirt_pool }}/{{ libvirt_configdrive }}',device=disk,bus=virtio,serial='cidata'"
- machine: 'q35'
- boot: 'hd,network,loader=/usr/share/OVMF/OVMF_CODE.fd'
- os_variant: 'ubuntu18.04'

libvirt_host_become: false

libvirt_netplan:
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: false
      accept-ra: false
    eth1:
      dhcp4: false
      dhcp6: false
      accept-ra: false

libvirt_pool: 'default'

libvirt_uri: 'qemu:///session'

libvirt_volumes:
- backing_vol: '{{ libvirt_backing_vol | mandatory }}'
  backing_vol_format: '{{ libvirt_backing_vol_format | mandatory }}'
  capacity: 100G
  format: 'qcow2'
  linked: false
  name: '{{ fqdn }}.qcow2'
  pool: '{{ libvirt_pool }}'
  prealloc_metadata: false
  state: present
