---
# Copyright (c) 2023 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

distribution_id:
- 'Debian'
- '11'

dnsmasq_config:
- ansible.builtin.copy:
    content: |
      bind-dynamic
      dhcp-authoritative
      dhcp-no-override
      dhcp-range=192.168.158.100,192.168.158.254,255.255.255.0
      no-resolv
      server=192.168.158.1
      strict-order
    dest: /etc/dnsmasq.d/demo
    mode: u=rw,g=r,o=
    group: root
    owner: root

libvirt_domain_autostart: no

libvirt_host_become: no

libvirt_netplan:
  ethernets:
    eth0:
      dhcp4: false
      dhcp6: false
      accept-ra: false

      addresses:
      - 192.168.158.25/24

      nameservers:
        addresses:
        - 192.168.158.1
      routes:
      - to: 0.0.0.0/0
        via: 192.168.158.1

libvirt_pool: 'default'

libvirt_uri: 'qemu:///session'

libvirt_volumes:
- backing_vol: 'debian-11-genericcloud-amd64.qcow2'
  backing_vol_format: 'qcow2'
  capacity: 5G
  format: 'qcow2'
  linked: no
  name: '{{ fqdn }}.qcow2'
  pool: '{{ libvirt_pool }}'
  prealloc_metadata: no
  state: present
