---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

devstack_user: stack

distribution_id:
- 'Ubuntu'
- '22.04'

libvirt_domain_autostart: false

libvirt_hardware:
- cpu: 'host'
- vcpus: '4'
- memory: '8192'
- virt_type: 'kvm'
- graphics: 'vnc,listen=socket'
- network: 'network=route-1-no-dhcp,model=virtio'
- disk: "vol='{{ libvirt_pool }}/{{ libvirt_volumes[0]['name'] }}',device=disk,bus=virtio"
- disk: "vol='{{ libvirt_pool }}/{{ libvirt_configdrive }}',device=disk,bus=virtio,serial='cidata'"
- os_variant: 'ubuntu18.04'

libvirt_host_become: false

libvirt_netplan:
  ethernets:
    eth0:
      dhcp4: false
      dhcp6: false
      accept-ra: false

      addresses:
      - 192.168.158.22/24

      nameservers:
        addresses:
        - 192.168.158.1
      routes:
      - to: 0.0.0.0/0
        via: 192.168.158.1

libvirt_pool: 'default'

libvirt_uri: 'qemu:///session'

libvirt_volumes:
- backing_vol: '{{ libvirt_backing_vol | mandatory }}'
  backing_vol_format: '{{ libvirt_backing_vol_format | mandatory }}'
  capacity: 32G
  format: 'qcow2'
  linked: false
  name: '{{ fqdn }}.qcow2'
  pool: '{{ libvirt_pool }}'
  prealloc_metadata: true
  state: present

packages:
- # Remove Python package simplejson which conflicts with DevStack
  # Ref.: https://bugs.launchpad.net/devstack/+bug/1871485
  name: python3-simplejson
  state: absent
- # Remove landscape-common to be able to remove its dependency python3-pyasn1-modules which conflicts with DevStack
  # Ref.: https://www.edureka.co/community/65075/error-cannot-uninstall-simplejson-not-able-install-ubuntu
  name: landscape-common
  state: absent
- # Remove Python package pyasn1-modules which conflicts with DevStack
  # Ref.: https://www.edureka.co/community/65075/error-cannot-uninstall-simplejson-not-able-install-ubuntu
  name: python3-pyasn1-modules
  state: absent

# Copy SSH authorized keys to ansible_user and devstack_user
ssh_authorized_keys: "{{ ssh_public_keys + ssh_public_keys | map('combine', { 'user': devstack_user }) }}"

# NOTE: Keep in sync with variable sudoers_config from group_vars/all.yml
sudoers_config:
- ansible.builtin.lineinfile:
    create: false # assert that file exist else system is probably not setup using cloud-init
    group: root
    line: '{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL'
    mode: u=r,g=r,o=
    owner: root
    path: /etc/sudoers.d/90-cloud-init-users
    state: present
- ansible.builtin.lineinfile:
    create: false # assert that file exist else system is probably not setup using cloud-init
    group: root
    line: '{{ devstack_user }} ALL=(ALL) NOPASSWD:ALL'
    mode: u=r,g=r,o=
    owner: root
    path: /etc/sudoers.d/90-cloud-init-users
    state: present

# NOTE: Keep in sync with variable users_config from group_vars/all.yml
users_config:
- name: root
  #password: '*'
  password_lock: true
  shell: '/bin/bash'
- name: '{{ ansible_user }}'
  #password: '*'
  password_lock: true
  shell: '/bin/bash'
- # home is not set to /opt/stack as suggested in DevStack's quick start guide, because
  # stack.sh fails if it has 0700 permissions which is the default e.g. on CentOS Stream 9.
  name: '{{ devstack_user }}'
  #password: '*'
  password_lock: true
  shell: '/bin/bash'
