---
# Copyright (c) 2024 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# TODO: Why does cloud-init's metadata service crawler take 200 seconds?

# ansible_host has to be explicitly defined here because Ansible controller cannot
# resolve the hostname as it is unknown outside of the isolated network
ansible_host: 192.168.153.26

cloudinit_userdata: |
  #cloud-config
  # autoinstall configuration
  # Ref.: https://ubuntu.com/server/docs/install/autoinstall

  autoinstall:
    version: 1
    network:
      version: 2
      ethernets:
        eth0:
          match:
            macaddress: 52:54:00:aa:bb:36
          dhcp4: false
          dhcp6: false
          accept-ra: false

          addresses:
          - 192.168.153.26/24

          nameservers:
            addresses:
            - 192.168.153.1
          routes:
          - to: 0.0.0.0/0
            via: 192.168.153.1
    proxy: http://192.168.153.2:8080/
    storage:
      layout:
        name: direct
    ssh:
      install-server: true
      allow-pw: false
    user-data:
      {{ cloudinit_userdata_default | indent(width=4) }}

# dhcpd_host_config cannot be a template because Ansible does not recursively evaluate variables.
# Ref.: https://github.com/ansible/ansible/issues/16351
dhcpd_host_config: |-
  hardware ethernet 52:54:00:aa:bb:36;
  fixed-address 192.168.153.26;

distribution_id:
- 'Ubuntu'
- '24.04'

libvirt_configdrive: !!null # disable cloud-init config drive

libvirt_domain_autostart: false

libvirt_hardware:
- cpu: 'host-passthrough,cache.mode=passthrough'
- vcpus: '2'
- memory: '12288' # required because ubuntu iso is downloaded to tmpfs during setup
- virt_type: 'kvm'
- graphics: 'vnc,listen=socket'
- network: 'network=isolated-2-no-dhcp,model=virtio,mac=52:54:00:aa:bb:36'
- disk: "vol='{{ libvirt_pool }}/{{ libvirt_volumes[0]['name'] }}',device=disk,bus=virtio"
- boot: 'hd,network'
- os_variant: 'ubuntu19.04'

libvirt_host_become: false

libvirt_pool: 'default'

libvirt_uri: 'qemu:///session'

libvirt_volumes:
- capacity: 20G
  format: 'qcow2'
  name: '{{ fqdn }}.qcow2'
  pool: '{{ libvirt_pool }}'
  prealloc_metadata: false
  state: present

os_architecture: x86_64

pxe_installer_client_mac: 52:54:00:aa:bb:36

# Inspired by Debian's OpenStack images
# Ref.: https://cdimage.debian.org/cdimage/openstack/
pxe_installer_kernel_parameters: >-
  console=tty0 console=ttyS0,115200 earlyprintk=ttyS0,115200 consoleblank=0 systemd.show_status=true
  http_proxy=http://192.168.153.2:8080/
