---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# How to build inventories
#
# In general Ansible provides three places where variables can be defined: hosts.yml, host_vars und group_vars.
# But what place is the most reasonable to define variables?
#
# Most important first: Do not define variables in hosts.yml! When inventories growth, the number of mappings between
# hosts and groups take up enough space in inventories that additional variable declarations reduces their readability.
#
# Hosts groups might not only be used to run different roles and tasks in playbooks, but also to selectively assign
# variables to hosts. But do not! Only use groups to organize playbooks, but do not use variable groups if possible.
# For example, suppose we would define all differences between hosts with the help of variable groups. In worst case,
# we would end up with one group per host. While the idiomatic way would be to define those host-specific variables in
# host_vars.
#
# In general, try to keep the number of groups small. Less groups result in more readable inventories. It will be easier
# to quickly parse the inventory (for humans), identify the mapping between hosts and groups and where variables are
# defined, either group_vars or host_vars.
#
# NOTE: Use valid hostnames for servers, e.g. do not use underscores! Else e.g. /etc/hostname and /etc/hosts will have
#       different hostnames listed. For valid characters in hostnames refer to https://en.wikipedia.org/wiki/Hostname !
#
# Have a look at Ansible's User Guide as well, which has a chapter on "How to build your inventory" [1].
#
# Ref.:
# [1] https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

all:
  hosts:

    lvrt-lcl-session:
      # dummy Ansible host to configure libvirt environment and QEMU/KVM domains of current Ansible user
    lvrt-lcl-session-srv-010-centos7:
      # demo local libvirt domain with CentOS 7
    lvrt-lcl-session-srv-011-centos8:
      # demo local libvirt domain with CentOS 8
    lvrt-lcl-session-srv-012-centos9:
      # demo local libvirt domain with CentOS 9
    lvrt-lcl-session-srv-020-debian10:
      # demo local libvirt domain with Debian 10 (Buster)
    lvrt-lcl-session-srv-021-debian11:
      # demo local libvirt domain with Debian 11 (Bullseye)
    lvrt-lcl-session-srv-022-debian12:
      # demo local libvirt domain with Debian 12 (Bookworm)
    lvrt-lcl-session-srv-030-ubuntu1804:
      # demo local libvirt domain with Ubuntu 18.04 LTS (Bionic Beaver)
    lvrt-lcl-session-srv-031-ubuntu2004:
      # demo local libvirt domain with Ubuntu 20.04 LTS (Focal Fossa)
    lvrt-lcl-session-srv-032-ubuntu2004-uefi:
      # demo local libvirt domain with UEFI Firmware
    lvrt-lcl-session-srv-033-ubuntu2004-2nd-volume:
      # demo local libvirt domain with 2nd storage volume
    lvrt-lcl-session-srv-034-ubuntu2204:
      # demo local libvirt domain with Ubuntu 22.04 LTS (Jammy Jellyfish)
    lvrt-lcl-session-srv-100-pxe-server-debian11:
      # local libvirt domain based on Debian 11 (Bullseye) that provides services to boot pxe clients
    lvrt-lcl-session-srv-110-pxe-client-debian11-bios:
      # local bios libvirt domain based on Debian 11 (Bullseye) that is installed via PXE provided by
      # lvrt-lcl-session-srv-100-pxe-server-debian11
    lvrt-lcl-session-srv-111-pxe-client-debian11-uefi:
      # local uefi libvirt domain based on Debian 11 (Bullseye) that is installed via PXE provided by
      # lvrt-lcl-session-srv-100-pxe-server-debian11
    lvrt-lcl-session-srv-112-pxe-client-debian12-bios:
      # local bios libvirt domain based on Debian 12 (Bookworm) that is installed via PXE provided by
      # lvrt-lcl-session-srv-100-pxe-server-debian11
    lvrt-lcl-session-srv-113-pxe-client-debian12-uefi:
      # local uefi libvirt domain based on Debian 12 (Bookworm) that is installed via PXE provided by
      # lvrt-lcl-session-srv-100-pxe-server-debian11
    lvrt-lcl-session-srv-120-pxe-client-ubuntu2004-bios:
      # local bios libvirt domain based on Ubuntu 20.04 LTS (Focal Fossa) that is installed via PXE provided by
      # lvrt-lcl-session-srv-100-pxe-server-debian11
    lvrt-lcl-session-srv-121-pxe-client-ubuntu2004-uefi:
      # local uefi libvirt domain based on Ubuntu 20.04 LTS (Focal Fossa) that is installed via PXE provided by
      # lvrt-lcl-session-srv-100-pxe-server-debian11
    lvrt-lcl-session-srv-122-pxe-client-ubuntu2204-bios:
      # local bios libvirt domain based on Ubuntu 22.04 LTS (Jammy Jellyfish) that is installed via PXE provided by
      # lvrt-lcl-session-srv-100-pxe-server-debian11
    lvrt-lcl-session-srv-123-pxe-client-ubuntu2204-uefi:
      # local uefi libvirt domain based on Ubuntu 22.04 LTS (Jammy Jellyfish) that is installed via PXE provided by
      # lvrt-lcl-session-srv-100-pxe-server-debian11
    lvrt-lcl-session-srv-130-pxe-client-centos8-bios:
      # local bios libvirt domain based on CentOS 8 Stream that is installed via PXE provided by
      # lvrt-lcl-session-srv-100-pxe-server-debian11
    lvrt-lcl-session-srv-131-pxe-client-centos8-uefi:
      # local uefi libvirt domain based on CentOS 8 Stream that is installed via PXE provided by
      # lvrt-lcl-session-srv-100-pxe-server-debian11
    lvrt-lcl-session-srv-132-pxe-client-centos9-bios:
      # local bios libvirt domain based on CentOS 9 Stream that is installed via PXE provided by
      # lvrt-lcl-session-srv-100-pxe-server-debian11
    lvrt-lcl-session-srv-133-pxe-client-centos9-uefi:
      # local uefi libvirt domain based on CentOS 9 Stream that is installed via PXE provided by
      # lvrt-lcl-session-srv-100-pxe-server-debian11
    lvrt-lcl-session-srv-200-devstack:
      # demo local libvirt domain that runs OpenStack's DevStack
    lvrt-lcl-session-srv-210-tripleo-standalone:
      # demo local libvirt domain that runs TripleO standalone on CentOS 8
    lvrt-lcl-session-srv-300-hwfp-server-debian11:
      # local libvirt domain based on Debian 11 (Bullseye) that provides a hardware fingerprinting service via pxe boot
    lvrt-lcl-session-srv-310-hwfp-client-debian11-bios:
      # local bios libvirt domain based on Debian 11 (Bullseye) which is booted via PXE from
      # lvrt-lcl-session-srv-300-hwfp-server-debian11 to fingerprint its hardware
    lvrt-lcl-session-srv-311-hwfp-client-debian11-uefi:
      # local uefi libvirt domain based on Debian 11 (Bullseye) which is booted via PXE from
      # lvrt-lcl-session-srv-300-hwfp-server-debian11 to fingerprint its hardware
    lvrt-lcl-system:
      # dummy Ansible host to configure libvirt environment and QEMU/KVM domains of root user

  children:
    # Dependency groups
    # NOTE: Every host must be part of exactly one build dependency group.
    # TODO: Add boot and shutdown dependency groups similar to build dependency groups?
    build_dependencies:
      children:
        build_level0:
          hosts:
            lvrt-lcl-system:
            lvrt-lcl-session:
        build_level1:
          hosts:
            lvrt-lcl-session-srv-010-centos7:
            lvrt-lcl-session-srv-011-centos8:
            lvrt-lcl-session-srv-012-centos9:
            lvrt-lcl-session-srv-020-debian10:
            lvrt-lcl-session-srv-021-debian11:
            lvrt-lcl-session-srv-022-debian12:
            lvrt-lcl-session-srv-030-ubuntu1804:
            lvrt-lcl-session-srv-031-ubuntu2004:
            lvrt-lcl-session-srv-032-ubuntu2004-uefi:
            lvrt-lcl-session-srv-033-ubuntu2004-2nd-volume:
            lvrt-lcl-session-srv-034-ubuntu2204:
            lvrt-lcl-session-srv-100-pxe-server-debian11:
            lvrt-lcl-session-srv-200-devstack:
            lvrt-lcl-session-srv-210-tripleo-standalone:
            lvrt-lcl-session-srv-300-hwfp-server-debian11:
        build_level2:
          hosts:
            lvrt-lcl-session-srv-110-pxe-client-debian11-bios:
            lvrt-lcl-session-srv-111-pxe-client-debian11-uefi:
            lvrt-lcl-session-srv-112-pxe-client-debian12-bios:
            lvrt-lcl-session-srv-113-pxe-client-debian12-uefi:
            lvrt-lcl-session-srv-120-pxe-client-ubuntu2004-bios:
            lvrt-lcl-session-srv-121-pxe-client-ubuntu2004-uefi:
            lvrt-lcl-session-srv-122-pxe-client-ubuntu2204-bios:
            lvrt-lcl-session-srv-123-pxe-client-ubuntu2204-uefi:
            lvrt-lcl-session-srv-130-pxe-client-centos8-bios:
            lvrt-lcl-session-srv-131-pxe-client-centos8-uefi:
            lvrt-lcl-session-srv-132-pxe-client-centos9-bios:
            lvrt-lcl-session-srv-133-pxe-client-centos9-uefi:
            lvrt-lcl-session-srv-310-hwfp-client-debian11-bios:
            lvrt-lcl-session-srv-311-hwfp-client-debian11-uefi:

    # Virtual groups
    # NOTE: Hosts might or might not be part of one or several virtual groups.
    cloud:
      children:
        bmtl:
          hosts:
        lvrt:
          hosts:
            lvrt-lcl-session-srv-010-centos7:
            lvrt-lcl-session-srv-011-centos8:
            lvrt-lcl-session-srv-012-centos9:
            lvrt-lcl-session-srv-020-debian10:
            lvrt-lcl-session-srv-021-debian11:
            lvrt-lcl-session-srv-022-debian12:
            lvrt-lcl-session-srv-030-ubuntu1804:
            lvrt-lcl-session-srv-031-ubuntu2004:
            lvrt-lcl-session-srv-032-ubuntu2004-uefi:
            lvrt-lcl-session-srv-033-ubuntu2004-2nd-volume:
            lvrt-lcl-session-srv-034-ubuntu2204:
            lvrt-lcl-session-srv-100-pxe-server-debian11:
            lvrt-lcl-session-srv-110-pxe-client-debian11-bios:
            lvrt-lcl-session-srv-111-pxe-client-debian11-uefi:
            lvrt-lcl-session-srv-112-pxe-client-debian12-bios:
            lvrt-lcl-session-srv-113-pxe-client-debian12-uefi:
            lvrt-lcl-session-srv-120-pxe-client-ubuntu2004-bios:
            lvrt-lcl-session-srv-121-pxe-client-ubuntu2004-uefi:
            lvrt-lcl-session-srv-122-pxe-client-ubuntu2204-bios:
            lvrt-lcl-session-srv-123-pxe-client-ubuntu2204-uefi:
            lvrt-lcl-session-srv-130-pxe-client-centos8-bios:
            lvrt-lcl-session-srv-131-pxe-client-centos8-uefi:
            lvrt-lcl-session-srv-132-pxe-client-centos9-bios:
            lvrt-lcl-session-srv-133-pxe-client-centos9-uefi:
            lvrt-lcl-session-srv-200-devstack:
            lvrt-lcl-session-srv-210-tripleo-standalone:
            lvrt-lcl-session-srv-300-hwfp-server-debian11:
            lvrt-lcl-session-srv-310-hwfp-client-debian11-bios:
            lvrt-lcl-session-srv-311-hwfp-client-debian11-uefi:
        ostk:
          children:
        ostk_project:
          children:

    svc:
      children:
        svc_devstack:
          hosts:
            lvrt-lcl-session-srv-200-devstack:
        svc_dhcpd:
          hosts:
            lvrt-lcl-session-srv-100-pxe-server-debian11:
            lvrt-lcl-session-srv-300-hwfp-server-debian11:
        svc_httpd:
          hosts:
            lvrt-lcl-session-srv-100-pxe-server-debian11:
        svc_libvirt:
          hosts:
            lvrt-lcl-session:
            lvrt-lcl-system:
        svc_pxe_hwfp:
          hosts:
            lvrt-lcl-session-srv-300-hwfp-server-debian11:
        svc_pxe_installer:
          hosts:
            lvrt-lcl-session-srv-100-pxe-server-debian11:
        svc_tftpd:
          hosts:
            lvrt-lcl-session-srv-100-pxe-server-debian11:
            lvrt-lcl-session-srv-300-hwfp-server-debian11:
        svc_tripleo_standalone:
          hosts:
            lvrt-lcl-session-srv-210-tripleo-standalone:

    pkg:
      children:
        pkg_ansible:
          hosts:
            #lvrt-lcl-session-srv-010-centos7: # TODO: Reenable once role jm1.packages.ansible supports CentOS 7
            #lvrt-lcl-session-srv-011-centos8: # TODO: Reenable once role jm1.packages.ansible supports CentOS 8
            #lvrt-lcl-session-srv-012-centos9: # TODO: Reenable once role jm1.packages.ansible supports CentOS 9
            lvrt-lcl-session-srv-020-debian10:
            lvrt-lcl-session-srv-021-debian11:
            lvrt-lcl-session-srv-022-debian12:
            lvrt-lcl-session-srv-030-ubuntu1804:
            lvrt-lcl-session-srv-031-ubuntu2004:
            lvrt-lcl-session-srv-034-ubuntu2204:
            lvrt-lcl-session-srv-200-devstack: # DevStack does not require Ansible but it is useful for development
        pkg_git:
          hosts:
            lvrt-lcl-session-srv-010-centos7:
            lvrt-lcl-session-srv-011-centos8:
            lvrt-lcl-session-srv-012-centos9:
            lvrt-lcl-session-srv-020-debian10:
            lvrt-lcl-session-srv-021-debian11:
            lvrt-lcl-session-srv-022-debian12:
            lvrt-lcl-session-srv-030-ubuntu1804:
            lvrt-lcl-session-srv-031-ubuntu2004:
            lvrt-lcl-session-srv-034-ubuntu2204:

