---
# Copyright (c) 2020 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Manage sudo configuration
  loop: '{{ sudoers|default([]) }}'
  lineinfile:
    attributes: '{{ item.attributes|default(omit) }}'
    backrefs: '{{ item.backrefs|default(omit) }}'
    backup: '{{ item.backup|default(omit) }}'
    create: '{{ item.create|default(true) }}'
    firstmatch: '{{ item.firstmatch|default(omit) }}'
    group: "{{ item.group|default('root') }}"
    insertafter: '{{ item.insertafter|default(omit) }}'
    insertbefore: '{{ item.insertbefore|default(omit) }}'
    line: '{{ item.line|mandatory }}'
    mode: "{{ item.mode|default('u=r,g=r,o=') }}"
    others: '{{ item.others|default(omit) }}'
    owner: "{{ item.owner|default('root') }}"
    path: "{{ item.path|mandatory }}"
    regexp: '{{ item.regex|default(item.line|regex_escape()) }}'
    selevel: '{{ item.selevel|default(omit) }}'
    serole: '{{ item.serole|default(omit) }}'
    setype: '{{ item.setype|default(omit) }}'
    seuser: '{{ item.seuser|default(omit) }}'
    state: "{{ item.state|default('present') }}"
    unsafe_writes: "{{ item.unsafe_writes|default(omit) }}"
    validate: "{{ item.validate|default(omit) }}"
  register: sudoers_result

- name: Debug role variables
  debug:
    msg:
      sudoers_result: '{{ sudoers_result }}'
  tags:
    - never
    - debug
