---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Manage services using Ansible's service module
  loop: '{{ services_config|default([]) }}'
  when: "'service' in item"
  service: "{{ item['service'] }}"
  register: services_config_service_result

- name: Manage systemd units using Ansible's systemd module
  loop: '{{ services_config|default([]) }}'
  when: "'systemd' in item"
  systemd: "{{ item['systemd'] }}"
  register: services_config_systemd_result

- name: Manage SysV services using Ansible's sysvinit module
  loop: '{{ services_config|default([]) }}'
  when: "'sysvinit' in item"
  sysvinit: "{{ item['sysvinit'] }}"
  register: services_config_sysvinit_result

- name: Debug role variables
  debug:
    msg:
      services_config_service_result: '{{ services_config_service_result }}'
      services_config_systemd_result: '{{ services_config_systemd_result }}'
      services_config_sysvinit_result: '{{ services_config_sysvinit_result }}'
  tags:
    - never
    - debug
