---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Install dependencies of collection jm1.pkg
  import_role:
    name: jm1.pkg.setup # If Ansible raises "ERROR! the role 'jm1.pkg.setup' was not found" then you might use the
                        # ansible-galaxy and the provided requirements.yml to install all missing role dependencies.

- name: Satisfy requirements
  jm1.pkg.meta_pkg:
    name: "jm1-sshd"
    version: "1"
    depends:
    - openssh-server

- name: Change blocks in sshd configuration
  loop: '{{ sshd_config|default([]) }}'
  when: "'blockinfile' in item"
  blockinfile: "{{ item['blockinfile'] }}"
  register: sshd_config_blockinfile_result
  notify:
  - 'Restart sshd service to apply changes'

- name: Copy files to sshd configuration
  loop: '{{ sshd_config|default([]) }}'
  when: "'copy' in item"
  copy: "{{ item['copy'] }}"
  register: sshd_config_copy_result
  notify:
  - 'Restart sshd service to apply changes'

- name: Change debconf selections for sshd
  loop: '{{ sshd_config|default([]) }}'
  when: "'debconf' in item"
  debconf: "{{ item['debconf'] }}"
  register: sshd_config_debconf_result
  notify:
  - 'Restart sshd service to apply changes'

- name: Manage files in sshd configuration
  loop: '{{ sshd_config|default([]) }}'
  when: "'file' in item"
  file: "{{ item['file'] }}"
  register: sshd_config_file_result
  notify:
  - 'Restart sshd service to apply changes'

- name: Change lines in sshd configuration
  loop: '{{ sshd_config|default([]) }}'
  when: "'lineinfile' in item"
  lineinfile: "{{ item['lineinfile'] }}"
  register: sshd_config_lineinfile_result
  notify:
  - 'Restart sshd service to apply changes'

- name: Generate sshd configuration from templates
  loop: '{{ sshd_config|default([]) }}'
  when: "'template' in item"
  template: "{{ item['template'] }}"
  register: sshd_config_template_result
  notify:
  - 'Restart sshd service to apply changes'

- name: Manage sshd service
  service:
    enabled: '{{ sshd_service_enabled }}'
    name: '{{ sshd_service_name }}'
    state: '{{ sshd_service_state }}'

- name: Debug role variables
  debug:
    msg:
      sshd_config_blockinfile_result: '{{ sshd_config_blockinfile_result }}'
      sshd_config_copy_result: '{{ sshd_config_copy_result }}'
      sshd_config_debconf_result: '{{ sshd_config_debconf_result }}'
      sshd_config_file_result: '{{ sshd_config_file_result }}'
      sshd_config_lineinfile_result: '{{ sshd_config_lineinfile_result }}'
      sshd_config_template_result: '{{ sshd_config_template_result }}'
  tags:
    - never
    - debug
