---
# No need to update apt cache here because role jm1.pkg.setup handles apt cache updates already

- name: Satisfy requirements
  jm1.pkg.meta_pkg:
    name: "jm1-dhcpd"
    version: "1"
    depends:
    - isc-dhcp-server

# "If you are here to restrict what interfaces should dhcpd listen on,
#  be aware that dhcpd listens *only* on interfaces for which it finds subnet
#  declaration in dhcpd.conf. It means that explicitly enumerating interfaces
#  also on command line should not be required in most cases."
# Ref.: /etc/sysconfig/dhcpd on Red Hat Enterprise Linux or CentOS

- name: Configure /etc/dhcp/dhcpd.conf
  template:
    dest: /etc/dhcp/dhcpd.conf
    group: root
    mode: u=rw,g=r,o=
    owner: root
    src: etc/dhcp/dhcpd.conf.j2
  notify:
  - 'Restart DHCP IPv4 service to apply changes'

- name: Configure /etc/dhcp/dhcpd6.conf
  template:
    dest: /etc/dhcp/dhcpd6.conf
    group: root
    mode: u=rw,g=r,o=
    owner: root
    src: etc/dhcp/dhcpd6.conf.j2
  notify:
  - 'Restart DHCP IPv6 service to apply changes'

# Debian provides a single service for DHCP IPv4 and DHCP IPv6 only

- name: Manage DHCP IPv4 and DHCP IPv6 service
  service:
    name: '{{ dhcpd_service_name }}'
    state: '{{ dhcpd_service_state }}'
    enabled: '{{ dhcpd_service_enabled }}'
