---
# Copyright (c) 2023 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Assert task definitions exist for creating install-config.yaml and other manifests
  when: openshift_ipi_config | mandatory | length == 0
  ansible.builtin.fail:
    msg: >-
      Variable 'openshift_ipi_config' must define tasks which creating install-config.yaml and other manifests for
      openshift-baremetal-install.

- name: Verify task definitions which create install-config.yaml and other manifests
  when: item is not mapping
        or (item.keys() | difference(['become', 'become_exe', 'become_flags', 'become_method', 'become_user',
                                      'environment', 'when'])) | list | length != 1
  ansible.builtin.fail:
    msg: >-
      Unsupported keyword or multiple module definitions found:
      {{ (item.keys() | difference(['become', 'become_exe', 'become_flags', 'become_method', 'become_user',
                                    'environment', 'when'])) | join(', ') }}.
  # Ansible will evaluate 'loop' when handling conditionals aka 'when'. When openshift_ipi_config is not defined
  # Ansible's mandatory filter will raise an exception while evaluating 'when' and thus 'loop'. For hosts which are
  # supposed to skip this role, e.g. because they are not in group svc_openshift_ipi, this is undesired, so the
  # mandatory filter cannot be used here. Handling undefined variables is done in a separate task before.
  loop: '{{ openshift_ipi_config | default([]) }}'

- name: Install dependencies of collection jm1.pkg
  ansible.builtin.import_role:
    name: jm1.pkg.setup # If Ansible raises "ERROR! the role 'jm1.pkg.setup' was not found" then you might use the
                        # ansible-galaxy and the provided requirements.yml to install all missing role dependencies.

- name: Satisfy requirements
  jm1.pkg.meta_pkg:
    name: "jm1-cloudy-openshift-ipi"
    version: "1"
    depends:
    # setfacl tool is used to set permissions on temporary files when becoming an unprivileged user
    # Ref.: https://stackoverflow.com/questions/46352173/ansible-failed-to-set-permissions-on-the-temporary#comment116424403_56379678
    - acl

- name: Expand paths for Ansible user
  become: false
  ansible.builtin.stat:
    path: '{{ item }}'
  loop:
  - '~'
  - '{{ openshift_ipi_config_dir }}'
  - '{{ openshift_ipi_install_dir }}'
  - '{{ openshift_ipi_pullsecret_file }}'
  register: openshift_ipi_paths

- name: Extract paths for Ansible user
  ansible.builtin.set_fact:
    # openshift_ipi_paths.results.*.stat.path is returned for existing paths only
    openshift_ipi_home_dir: '{{ openshift_ipi_paths.results.0.invocation.module_args.path }}'
    openshift_ipi_config_dir: '{{ openshift_ipi_paths.results.1.invocation.module_args.path }}'
    openshift_ipi_install_dir: '{{ openshift_ipi_paths.results.2.invocation.module_args.path }}'
    openshift_ipi_pullsecret_file: '{{ openshift_ipi_paths.results.3.invocation.module_args.path }}'

- name: Create config directory for openshift-baremetal-install
  ansible.builtin.file:
    group: '{{ ansible_user }}'
    mode: u=rwx,g=rx,o=
    owner: '{{ ansible_user }}'
    path: '{{ openshift_ipi_config_dir }}'
    state: directory

- name: Check if manifests have been generated
  ansible.builtin.stat:
    path: '{{ openshift_ipi_config_dir }}/manifests'
  register: openshift_ipi_path_manifests_marker

- name: Check if OpenShift Installer-provisioned installation (IPI) has been started, failed or finished
  ansible.builtin.stat:
    path: '{{ openshift_ipi_config_dir }}/auth/kubeconfig'
  register: openshift_ipi_path_init_marker

- name: Check if cluster has been bootstrapped
  ansible.builtin.stat:
    path: '{{ openshift_ipi_config_dir }}/.ipi-bootstrap-complete'
  register: openshift_ipi_path_bootstrap_marker

- name: Check if cluster has been installed
  ansible.builtin.stat:
    path: '{{ openshift_ipi_config_dir }}/.ipi-install-complete'
  register: openshift_ipi_path_install_marker

- name: Ensure markers are consistent
  ansible.builtin.assert:
    that:
      - openshift_ipi_path_init_marker.stat.exists or not openshift_ipi_path_bootstrap_marker.stat.exists
      - openshift_ipi_path_bootstrap_marker.stat.exists or not openshift_ipi_path_install_marker.stat.exists

- name: Create install-config.yaml and other manifests for openshift-baremetal-install
  # openshift-baremetal-install will delete install-config.yaml when generating manifests
  # openshift-baremetal-install will delete manifests when cluster has been created
  when: not openshift_ipi_path_manifests_marker.stat.exists and not openshift_ipi_path_init_marker.stat.exists
  # Values for 'become' and related keywords will not be inherited from the role's caller when using 'omit' as
  # default.
  become: "{{ item['become'] | default(omit) }}"
  become_exe: "{{ item['become_exe'] | default(omit) }}"
  become_flags: "{{ item['become_flags'] | default(omit) }}"
  become_method: "{{ item['become_method'] | default(omit) }}"
  become_user: "{{ item['become_user'] | default(omit) }}"
  jm1.ansible.execute_module:
    name: "{{ (item.keys() | difference(['become', 'become_exe', 'become_flags', 'become_method', 'become_user',
                                          'environment', 'when'])) | first }}"
    args: "{{ item[(item.keys() | difference(['become', 'become_exe', 'become_flags', 'become_method', 'become_user',
                                              'environment', 'when'])) | first] }}"
    when: "{{ item['when'] | default(omit) }}"
  environment: "{{ item['environment'] | default(omit) }}"
  loop: "{{ openshift_ipi_config | default([]) }}"

- name: Create pull secret for openshift-baremetal-install
  when: openshift_ipi_pullsecret | default(None) != None
  ansible.builtin.template:
    dest: '{{ openshift_ipi_pullsecret_file }}'
    group: '{{ ansible_user }}'
    mode: u=rw,g=r,o=
    owner: '{{ ansible_user }}'
    src: pull-secret.txt.j2

- name: Extract openshift-baremetal-install
  become: true
  become_flags: '--preserve-env=PATH'
  ansible.builtin.shell: # noqa risky-shell-pipe
    chdir: '{{ openshift_ipi_home_dir }}'
    cmd: |
      oc adm release extract \
        {{ ('--registry-config ' + openshift_ipi_pullsecret_file)
           if openshift_ipi_pullsecret | default(None) != None
           else ''
        }} \
        --command=openshift-baremetal-install \
        --to '{{ openshift_ipi_install_dir }}/' \
        '{{ openshift_ipi_release_image | mandatory }}'
    creates: '{{ openshift_ipi_install_dir }}/openshift-baremetal-install'

- name: Get openshift-baremetal-install version
  become: false
  changed_when: false
  ansible.builtin.command:
    chdir: '{{ openshift_ipi_home_dir }}'
    cmd: openshift-baremetal-install version
  register: openshift_ipi_openshift_install_version

- name: Print openshift-baremetal-install version
  ansible.builtin.debug:
    msg: '{{ openshift_ipi_openshift_install_version.stdout_lines }}'

- name: Generate manifests for OpenShift Installer-provisioned installation (IPI)
  # openshift-baremetal-install will delete manifests when cluster has been created
  when: not openshift_ipi_path_init_marker.stat.exists
  # Own manifests by Ansible user
  become: true
  become_flags: '--preserve-env=PATH'
  become_user: '{{ ansible_user }}'
  ansible.builtin.command:
    chdir: '{{ openshift_ipi_home_dir }}'
    cmd: openshift-baremetal-install --dir '{{ openshift_ipi_config_dir }}' --log-level debug create manifests
    creates: '{{ openshift_ipi_config_dir }}/manifests'

- name: Run OpenShift Installer-provisioned installation (IPI)
  when: not openshift_ipi_path_bootstrap_marker.stat.exists
  # Run command as Ansible user and preserve environment variable SSH_AUTH_SOCK
  # which is required for SSH agent forwarding to the bootstrap virtual machine
  become: true
  become_user: '{{ ansible_user }}'
  become_flags: '--preserve-env=PATH,SSH_AUTH_SOCK'
  ansible.builtin.shell:
    chdir: '{{ openshift_ipi_home_dir }}'
    cmd: |
      # The sudo below is required to run the openshift-baremetal-install command with all group memberships, esp. kvm
      # and libvirt. Without sudo the user which runs openshift-baremetal-install will only be in group ansible.
      sudo -u '{{ ansible_user }}' --preserve-env=SSH_AUTH_SOCK \
        openshift-baremetal-install --dir '{{ openshift_ipi_config_dir }}' --log-level debug create cluster
    creates: '{{ openshift_ipi_config_dir }}/auth/kubeconfig'

- name: Wait until cluster has been bootstrapped
  when: not openshift_ipi_path_bootstrap_marker.stat.exists
  become: false
  changed_when: false
  ansible.builtin.command:
    chdir: '{{ openshift_ipi_home_dir }}'
    cmd: openshift-baremetal-install --dir '{{ openshift_ipi_config_dir }}' --log-level debug wait-for bootstrap-complete

- name: Create a marker file to signal successful bootstrapping of the cluster
  ansible.builtin.copy:
    content: |
      # 2023 Jakob Meng, <jakobmeng@web.de>
      # Cluster has been bootstrapped successfully with OpenShift Installer-provisioned installation (IPI)
    dest: '{{ openshift_ipi_config_dir }}/.ipi-bootstrap-complete'
    mode: u=rw,g=r,o=r
    group: '{{ ansible_user }}'
    owner: '{{ ansible_user }}'

- name: Wait for cluster installation to complete
  when: not openshift_ipi_path_install_marker.stat.exists
  become: false
  changed_when: false
  ansible.builtin.command:
    chdir: '{{ openshift_ipi_home_dir }}'
    cmd: openshift-baremetal-install --dir '{{ openshift_ipi_config_dir }}' --log-level debug wait-for install-complete

- name: Create a marker file to signal successful completion of OpenShift Installer-provisioned installation (IPI)
  ansible.builtin.copy:
    content: |
      # 2023 Jakob Meng, <jakobmeng@web.de>
      # Cluster has been installed sucessfully with OpenShift Installer-provisioned installation (IPI).
    dest: '{{ openshift_ipi_config_dir }}/.ipi-install-complete'
    mode: u=rw,g=r,o=r
    group: '{{ ansible_user }}'
    owner: '{{ ansible_user }}'
