---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: 'Generate initramfs images'
  ansible.builtin.shell:
    cmd: '{{ initrd_cmd }}' # noqa command-instead-of-shell
  notify:
  - "Reboot to apply changes after initramfs images have been (re)generated"

- name: 'Reboot to apply changes after initramfs images have been (re)generated'
  ansible.builtin.reboot:
