---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# Variable distribution_id is a list which uniquely identifies a distribution release, e.g.
#  [ 'CentOS', '8' ] for CentOS 8 (both Core and Stream)
#  [ 'Debian', '10' ] for Debian 10 (Buster)
#  [ 'Debian', 'Unstable' ] for Debian Unstable (Sid)
#  [ 'Red Hat Enterprise Linux', '8' ]` for Red Hat Enterprise Linux (RHEL) 8
#  [ 'Ubuntu', '20.04' ] for Ubuntu 20.04 LTS (Focal Fossa)
distribution_id:
- '{{ ansible_facts.distribution }}'
- # Use major and minor version for Ubuntu, e.g. Ubuntu 18.04 LTS (Bionic Beaver) or Ubuntu 20.04 LTS (Focal Fossa).
  # Use major version in title case for unknown Debian releases, i.e. the major version is not a number and not 'NA',
  # e.g. when VERSION_ID is not set in /etc/os-release and lsb_release is available on that host, then
  # ansible_facts.distribution_major_version is defined as 'testing' which will be converted to 'Testing'.
  # Use major version for all other distributions, e.g. CentOS 7, Debian 10 (Buster) or Red Hat Enterprise Linux 8.
  "{{ ansible_facts.distribution_version if ansible_facts.distribution == 'Ubuntu' else
      ansible_facts.distribution_major_version|title if
        ansible_facts.distribution == 'Debian' and
        ansible_facts.distribution_major_version is not number and
        ansible_facts.distribution_major_version != 'NA' else
          ansible_facts.distribution_major_version }}"

tripleo_standalone_branch: master

tripleo_standalone_cloud_name: 'tripleo_standalone'

tripleo_standalone_cloud_domain: '{{ dns_suffix }}'

tripleo_standalone_control_virtual_ip: !!null # is set in host_vars

tripleo_standalone_home_dir: '/home/{{ tripleo_standalone_user }}'

tripleo_standalone_local_ip: !!null # is set in host_vars

tripleo_standalone_neutron_dns_domain: '{{ dns_suffix }}'

tripleo_standalone_neutron_public_interface: !!null # is set in host_vars

tripleo_standalone_parameters: |
  parameter_defaults:
    # domain name used by the host
    CloudDomain: {{ tripleo_standalone_cloud_domain }}
    CloudName: {{ tripleo_standalone_cloud_name }}
    # default gateway example
    #ControlPlaneStaticRoutes:
    #- ip_netmask: 0.0.0.0/0
    #  next_hop: 192.168.0.1
    #  default: true
    ControlPlaneStaticRoutes: []
    Debug: true
    DeploymentUser: {{ tripleo_standalone_user }}
    DnsServers:
      - 1.1.1.1
      - 8.8.8.8
    DockerInsecureRegistryAddress:
      - {{ tripleo_standalone_local_ip|ipaddr('address') }}:8787
    InterfaceLocalMtu: 1500
    # needed for vip & pacemaker
    KernelIpNonLocalBind: 1
    NeutronPublicInterface: {{ tripleo_standalone_neutron_public_interface }}
    NeutronDnsDomain: {{ tripleo_standalone_neutron_dns_domain }}
    # re-use ctlplane bridge for public net, defined in the standalone
    # net config (do not change unless you know what you're doing)
    NeutronBridgeMappings: datacentre:br-ctlplane
    NeutronPhysicalBridge: br-ctlplane
    # enable to force metadata for public net
    #NeutronEnableForceMetadata: true
    # Needed if running in a VM, not needed if on baremetal, because deeply nested virtual machines are slow or do crash
    NovaComputeLibvirtType: qemu
    SELinuxMode: permissive
    StandaloneEnableRoutedNetworks: false
    StandaloneHomeDir: {{ tripleo_standalone_home_dir }}

tripleo_standalone_repo_uri: 'https://trunk.rdoproject.org/centos8-{{ tripleo_standalone_branch }}/component/tripleo/current/delorean.repo'

tripleo_standalone_repos: 'current'

tripleo_standalone_user: 'stack'
