---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

tripleo_standalone_branch: master

tripleo_standalone_cloud_name: 'tripleo_standalone'

tripleo_standalone_cloud_domain: '{{ dns_suffix }}'

tripleo_standalone_control_virtual_ip: !!null # is set in host_vars

tripleo_standalone_home_dir: '/home/{{ tripleo_standalone_user }}'

tripleo_standalone_local_ip: !!null # is set in host_vars

tripleo_standalone_neutron_dns_domain: '{{ dns_suffix }}'

tripleo_standalone_neutron_public_interface: !!null # is set in host_vars

tripleo_standalone_parameters: |
  parameter_defaults:
    # domain name used by the host
    CloudDomain: {{ tripleo_standalone_cloud_domain }}
    CloudName: {{ tripleo_standalone_cloud_name }}
    # default gateway example
    #ControlPlaneStaticRoutes:
    #- ip_netmask: 0.0.0.0/0
    #  next_hop: 192.168.0.1
    #  default: true
    ControlPlaneStaticRoutes: []
    Debug: true
    DeploymentUser: {{ tripleo_standalone_user }}
    DnsServers:
      - 1.1.1.1
      - 8.8.8.8
    DockerInsecureRegistryAddress:
      - {{ tripleo_standalone_local_ip|ipaddr('address') }}:8787
    InterfaceLocalMtu: 1500
    # needed for vip & pacemaker
    KernelIpNonLocalBind: 1
    NeutronPublicInterface: {{ tripleo_standalone_neutron_public_interface }}
    NeutronDnsDomain: {{ tripleo_standalone_neutron_dns_domain }}
    # re-use ctlplane bridge for public net, defined in the standalone
    # net config (do not change unless you know what you're doing)
    NeutronBridgeMappings: datacentre:br-ctlplane
    NeutronPhysicalBridge: br-ctlplane
    # enable to force metadata for public net
    #NeutronEnableForceMetadata: true
    # Needed if running in a VM, not needed if on baremetal, because deeply nested virtual machines are slow or do crash
    NovaComputeLibvirtType: qemu
    SELinuxMode: permissive
    StandaloneEnableRoutedNetworks: false
    StandaloneHomeDir: {{ tripleo_standalone_home_dir }}

tripleo_standalone_repo_uri: 'https://trunk.rdoproject.org/centos8-{{ tripleo_standalone_branch }}/component/tripleo/current/delorean.repo'

tripleo_standalone_repos: 'current'

tripleo_standalone_user: 'stack'
