---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

openstack_auth: '{{ omit }}'

openstack_cloud: '{{ omit }}'

openstack_interface: '{{ omit }}'

openstack_network_ports: []

openstack_server_auto_ip: '{{ omit }}'

openstack_server_boot_from_volume: '{{ omit }}'

openstack_server_boot_volume: !!null

openstack_server_config_drive: '{{ omit }}'

openstack_server_delete_fip: '{{ omit }}'

openstack_server_flavor: '{{ omit }}'

openstack_server_flavor_include: '{{ omit }}'

openstack_server_flavor_ram: '{{ omit }}'

openstack_server_floating_ip_pools: '{{ omit }}'

openstack_server_floating_ips: []

openstack_server_image: '{{ omit }}'

openstack_server_image_exclude: '{{ omit }}'

openstack_server_key_name: '{{ omit }}'

openstack_server_meta: '{{ omit }}'

openstack_server_name: '{{ fqdn|mandatory }}'

openstack_server_network: '{{ omit }}'

openstack_server_reuse_ips: '{{ omit }}'

openstack_server_scheduler_hints: '{{ omit }}'

openstack_server_security_groups: '{{ omit }}'

openstack_server_terminate_volume: '{{ omit }}'

openstack_server_userdata: '{{ cloudinit_userdata|default(omit) }}'

openstack_server_volume_size: '{{ omit }}'

openstack_server_volumes: []

state: present
