---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

openstack_auth: '{{ omit }}'

openstack_cloud: '{{ omit }}'

openstack_interface: '{{ omit }}'

openstack_server_config:
  # floating_ips is set in openstack_server_floating_ips and will be ignored here
  # name is set in openstack_server_name and will be ignored here
  # nics will be expanded with ports listed in openstack_server_ports
  # state is set in state and will be ignored here

openstack_server_floating_ips: []

openstack_server_name: '{{ inventory_hostname }}'

openstack_server_ports: []

# Possible server states: [active, paused, suspended, shutoff, shelved, shelved_offloaded]
# Ref.: https://docs.openstack.org/api-guide/compute/server_concepts.html
openstack_server_state: active

state: present
