---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Fail if required vars are not set
  fail:
  when: >
    libvirt_domain == None or libvirt_domain|length == 0 or
    libvirt_uri == None or libvirt_uri|length == 0

- name: Fetch server info
  community.libvirt.virt:
    command: info
    uri: '{{ libvirt_uri }}'
  register: virt_result

- name: Prepare server info
  set_fact:
    libvirt_server_info: '{{ virt_result[libvirt_domain] }}'
  when: libvirt_domain in virt_result

- name: Nullify server info
  set_fact:
    libvirt_server_info: !!null
  when: libvirt_domain not in virt_result

- name: Cleanup temporary results
  set_fact:
    virt_result: !!null

- name: Debug role variables
  debug:
    msg:
      libvirt_server_info: '{{ libvirt_server_info }}'
  tags:
    - never
    - debug
