---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

openstack_auth: '{{ omit }}'

openstack_cloud: '{{ omit }}'

openstack_interface: '{{ omit }}'

openstack_network_ports: []

openstack_netplan_extra: ''

openstack_server_name: !!null
