---
# Copyright (c) 2020-2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Load/Remove images as libvirt block storage volumes
  loop: '{{ libvirt_images|default([]) }}'
  jm1.libvirt.volume_import: "{{ item|combine({} if 'uri' in item else {'uri': libvirt_uri}) }}"
