---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# NOTE: Synchronize changes with roles/openstack_server/tasks/server_info.yml

- name: Fetch server info
  openstack.cloud.server_info:
    auth: '{{ openstack_auth }}'
    cloud: '{{ openstack_cloud }}'
    filters:
      name: '{{ openstack_server_name }}'
    interface: '{{ openstack_interface }}'
  register: openstack_server_info

- name: Enforce unique server names
  ansible.builtin.assert:
    that:
      openstack_server_info.openstack_servers|length < 2
    fail_msg: >-
        Found several servers sharing the same name:
        {{ openstack_server_info.openstack_servers|map(attribute='name')|join(' ') }}

- name: Postprocess server info
  ansible.builtin.set_fact:
    openstack_server_info: "{{ openstack_server_info.openstack_servers[0]
                               if openstack_server_info.openstack_servers|length > 1 else None }}"
