galaxy_info:
  role_name: openstack_volumes
  author: Jakob Meng
  description: Add/Remove OpenStack block storage volumes
  company: Hochschule Bonn-Rhein-Sieg
  license: license (GPLv3)

  min_ansible_version: 2.9

  platforms:
  # Ref.: https://galaxy.ansible.com/api/v1/platforms/
  - name: Debian
    versions:
    - buster
    - bullseye
    - bookworm

  galaxy_tags:
  - development
  - system

dependencies: []
