---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Add/Remove OpenStack security groups
  loop: '{{ openstack_security_groups|default([]) }}'
  openstack.cloud.security_group: "{{ item
    |combine({} if 'auth' in item else {'auth': openstack_auth})
    |combine({} if 'cloud' in item else {'cloud': openstack_cloud})
    |combine({} if 'interface' in item else {'interface': openstack_interface})
  }}"

- name: Add/Remove rules from a OpenStack security group
  loop: "{{ openstack_security_groups|default([])|subelements('rules') }}"
  when: item.0.state == 'present'
  openstack.cloud.security_group_rule:
    auth: '{{ openstack_auth }}'
    cloud: '{{ openstack_cloud }}'
    direction: '{{ item.1.direction|default(omit) }}'
    ethertype: '{{ item.1.ethertype|default(omit) }}'
    interface: '{{ openstack_interface|default(omit) }}'
    port_range_max: '{{ item.1.port_range_max|default(omit) }}'
    port_range_min: '{{ item.1.port_range_min|default(omit) }}'
    project: '{{ item.0.project|default(omit) }}'
    protocol: '{{ item.1.protocol|default(omit) }}'
    remote_group: '{{ item.1.remote_group|default(omit) }}'
    remote_ip_prefix: '{{ item.1.remote_ip_prefix|default(omit) }}'
    security_group: '{{ item.0.name|mandatory }}'
    state: '{{ item.1.state|default(present) }}'
