---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

devstack_admin_password: 'secret'

devstack_config: |
  # Minimum required config to get started with DevStack
  # Ref.:
  # https://docs.openstack.org/devstack/latest/
  # https://opendev.org/openstack/devstack/src/branch/master/samples/local.conf
  [[local|localrc]]
  ADMIN_PASSWORD={{ devstack_admin_password }}
  DATABASE_PASSWORD={{ devstack_database_password }}
  RABBIT_PASSWORD={{ devstack_rabbit_password }}
  SERVICE_PASSWORD={{ devstack_service_password }}

devstack_database_password: '{{ devstack_admin_password }}'

devstack_rabbit_password: '{{ devstack_admin_password }}'

devstack_service_password: '{{ devstack_admin_password }}'

devstack_user: 'stack'
