---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Add/Remove libvirt block storage volumes
  loop: "{{ libvirt_volumes|default([]) }}"
  jm1.libvirt.volume:
    capacity: '{{ item.capacity|mandatory }}'
    format: '{{ item.format|default(omit) }}'
    name: '{{ item.name|mandatory }}'
    pool: "{{ item.pool|mandatory }}"
    prealloc_metadata: '{{ item.prealloc_metadata|default(omit) }}'
    state: "{{ item.state|default('present') }}"
    uri: '{{ libvirt_uri }}'
  when: item.backing_vol|default(None) == None
  register: libvirt_volume_result

- name: Add/Remove libvirt block storage volume snapshots
  loop: "{{ libvirt_volumes|default([]) }}"
  jm1.libvirt.volume_snapshot:
    backing_vol: '{{ item.backing_vol|mandatory }}'
    backing_vol_format: '{{ item.backing_vol_format|default(omit) }}'
    capacity: '{{ item.capacity|default(omit) }}'
    format: '{{ item.format|default(omit) }}'
    linked: '{{ item.linked|default(omit) }}'
    name: '{{ item.name|mandatory }}'
    pool: "{{ item.pool|mandatory }}"
    prealloc_metadata: '{{ item.prealloc_metadata|default(omit) }}'
    state: "{{ item.state|default('present') }}"
    uri: '{{ libvirt_uri }}'
  when: item.backing_vol|default(None) != None
  register: libvirt_volume_snapshot_result

- name: Debug role variables
  debug:
    msg:
      libvirt_volume_result: '{{ libvirt_volume_result }}'
      libvirt_volume_snapshot_result: '{{ libvirt_volume_snapshot_result }}'
  tags:
    - never
    - debug
