---
# Copyright (c) 2023 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Verify task definitions specified in podman_config variable
  when: item is not mapping or (item.keys() | difference(['handlers', 'register', 'when'])) | list | length != 1
  ansible.builtin.fail:
    msg: >-
      Unsupported keyword or multiple module definitions found:
      {{ (item.keys() | difference(['handlers', 'register', 'when'])) | join(', ') }}.
  loop: '{{ podman_config | default([]) }}'

- name: Verify handler definitions specified in podman_config variable
  when: item.1 is not mapping or (item.1.keys() | difference(['register', 'when'])) | list | length != 1
  ansible.builtin.fail:
    msg: >-
      Unsupported keyword or multiple module definitions found:
      {{ (item.1.keys() | difference(['register', 'when'])) | join(', ') }}.
  loop: "{{ podman_config | default([]) | subelements('handlers', skip_missing=True) }}"

- name: Install dependencies of collection jm1.pkg
  ansible.builtin.import_role:
    name: jm1.pkg.setup # If Ansible raises "ERROR! the role 'jm1.pkg.setup' was not found" then you might use the
                        # ansible-galaxy and the provided requirements.yml to install all missing role dependencies.

- name: Satisfy requirements
  jm1.pkg.meta_pkg:
    name: "jm1-cloudy-podman"
    version: "1"
    depends:
    - podman

- name: Run tasks specified in podman_config variable
  jm1.ansible.execute_module:
    name: "{{ (item.keys() | difference(['handlers', 'register', 'when'])) | first }}"
    args: "{{ item[(item.keys() | difference(['handlers', 'register', 'when'])) | first] }}"
    register: "{{ item['register'] | default(omit) }}"
    when: item['when'] | default(omit)
  loop: "{{ podman_config | default([]) }}"
  register: podman_config_result
  notify:
  - 'Run Podman handlers to apply changes'
