---
# Copyright (c) 2021-2024 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

dhcpd_config:
- # Configure /etc/dhcp/dhcpd.conf
  copy:
    dest: /etc/dhcp/dhcpd.conf
    group: root
    mode: u=rw,g=r,o=
    owner: root
    src: "{{ distribution_id | first | lower | regex_replace('[^a-z0-9_]', '_') + '/etc/dhcp/dhcpd.conf' }}"

dhcpd6_config:
- # Configure /etc/dhcp/dhcpd6.conf
  copy:
    dest: /etc/dhcp/dhcpd6.conf
    group: root
    mode: u=rw,g=r,o=
    owner: root
    src: "{{ distribution_id | first | lower | regex_replace('[^a-z0-9_]', '_') + '/etc/dhcp/dhcpd6.conf' }}"

dhcpd_service_enabled: true

dhcpd_service_name: |-
  {{
    {
      'CentOS': 'dhcpd.service',
      'Debian': 'isc-dhcp-server',
      'Fedora': 'dhcpd.service',
      'Red_Hat_Enterprise_Linux': 'dhcpd.service',
      'Ubuntu': 'isc-dhcp-server'
    }[distribution_id | first | regex_replace('[^A-Za-z0-9_]', '_')]
  }}

dhcpd_service_state: 'started'

dhcpd6_service_enabled: true

dhcpd6_service_name: |-
  {{
    {
      'CentOS': 'dhcpd6.service',
      'Debian': 'isc-dhcp-server',
      'Fedora': 'dhcpd6.service',
      'Red_Hat_Enterprise_Linux': 'dhcpd6.service',
      'Ubuntu': 'isc-dhcp-server6'
    }[distribution_id | first | regex_replace('[^A-Za-z0-9_]', '_')]
  }}

dhcpd6_service_state: 'started'

# Variable distribution_id is a list which uniquely identifies a distribution release, e.g.
#  ['CentOS', '8'] for CentOS 8 (both Core and Stream)
#  ['Debian', '10'] for Debian 10 (Buster)
#  ['Red Hat Enterprise Linux', '8' ]` for Red Hat Enterprise Linux (RHEL) 8
#  ['Ubuntu', '20.04' ] for Ubuntu 20.04 LTS (Focal Fossa)
#
# NOTE: Version numbers for upcoming Debian releases are not stable. For example, when lsb_release is available, which
# is the default, Ansible will report 'n/a' for Debian's testing and unstable (Sid) distributions. When lsb_release
# has been uninstalled, the version string will be 'trixie/sid' or similar. In the past, 'NA' would be reported when
# lsb_release was not available and 'testing' or 'sid' when it was installed.
distribution_id:
- '{{ ansible_facts.distribution }}'
- # Use major and minor version for Ubuntu, e.g. Ubuntu 18.04 LTS (Bionic Beaver) or Ubuntu 20.04 LTS (Focal Fossa).
  # Use major version for all other distributions, e.g. CentOS 7, Debian 10 (Buster) or Red Hat Enterprise Linux 8.
  "{{ ansible_facts.distribution_version if ansible_facts.distribution == 'Ubuntu' else
      ansible_facts.distribution_major_version }}"
