---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

dhcpd_config:
- # Configure /etc/dhcp/dhcpd.conf
  copy:
    dest: /etc/dhcp/dhcpd.conf
    group: root
    mode: u=rw,g=r,o=
    owner: root
    src: "{{ distribution_id|join('-')|regex_replace('[^A-Za-z0-9_.-]', '-') + '/etc/dhcp/dhcpd.conf' }}"

dhcpd6_config:
- # Configure /etc/dhcp/dhcpd6.conf
  copy:
    dest: /etc/dhcp/dhcpd6.conf
    group: root
    mode: u=rw,g=r,o=
    owner: root
    src: "{{ distribution_id|join('-')|regex_replace('[^A-Za-z0-9_.-]', '-') + '/etc/dhcp/dhcpd6.conf' }}"

dhcpd_service_enabled: yes

dhcpd_service_name: |-
  {{
    {
      'CentOS_7': 'dhcpd.service',
      'CentOS_8': 'dhcpd.service',
      'Debian_10': 'isc-dhcp-server',
      'Debian_11': 'isc-dhcp-server',
      'Red_Hat_Enterprise_Linux_7': 'dhcpd.service',
      'Red_Hat_Enterprise_Linux_8': 'dhcpd.service',
      'Ubuntu_18_04': 'isc-dhcp-server',
      'Ubuntu_20_04': 'isc-dhcp-server'
    }[distribution_id|join('_')|regex_replace('[^A-Za-z0-9 _-]', '_')]
  }}

dhcpd_service_state: 'started'

dhcpd6_service_enabled: yes

dhcpd6_service_name: |-
  {{
    {
      'CentOS_7': 'dhcpd6.service',
      'CentOS_8': 'dhcpd6.service',
      'Debian_10': 'isc-dhcp-server',
      'Debian_11': 'isc-dhcp-server',
      'Red_Hat_Enterprise_Linux_7': 'dhcpd6.service',
      'Red_Hat_Enterprise_Linux_8': 'dhcpd6.service',
      'Ubuntu_18_04': 'isc-dhcp-server6',
      'Ubuntu_20_04': 'isc-dhcp-server6'
    }[distribution_id|join('_')|regex_replace('[^A-Za-z0-9 _-]', '_')]
  }}

dhcpd6_service_state: 'started'
