---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

impi_boot_persistent: no

ipmi_boot_device: 'default'

ipmi_host: !!null

ipmi_password: 'ADMIN'

ipmi_port: '{{ omit }}'

# Possible power states: ['on', 'off']
# Ref.: https://docs.ansible.com/ansible/latest/collections/community/general/ipmi_power_module.html
ipmi_power_state: 'on'

ipmi_uefiboot: no

ipmi_username: 'ADMIN'
