---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# This variable is supposed to be a safety guard and as such should be set
# as extra vars on the command line, *NOT* in  host_vars or group_vars!
force_ipmi_boot: false

# This variable is supposed to be a safety guard and as such should be set
# as extra vars on the command line, *NOT* in  host_vars or group_vars!
force_ipmi_power: false

# This variable is supposed to be a safety guard and as such should be set
# as extra vars on the command line, *NOT* in  host_vars or group_vars!
force_ipmi_boot_from_network: false

impi_boot_persistent: false

ipmi_boot_device: 'default'

ipmi_host: !!null # is set in host_vars

ipmi_password: 'ADMIN'

ipmi_port: '{{ omit }}'

# Possible power states: ['on', 'off']
# Ref.: https://docs.ansible.com/ansible/latest/collections/community/general/ipmi_power_module.html
ipmi_power_state: 'on'

ipmi_uefiboot: false

ipmi_username: 'ADMIN'
