---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Add/Remove SSH keys into OpenStack project
  loop: '{{ openstack_keypairs | default([]) }}'
  # Try to use item.comment as name and fallback to item.user, because multiple entries in openstack_keypairs might have
  # the same value for item.user. By default, openstack_keypairs is a copy of ssh_authorized_keys, which uses item.user to
  # identify all ssh authorized keys that should be added for this user, hence item.user is ambiguous.
  #
  # Allowed characters are A-Z, a-z, 0-9, space, minus and underscore.
  # Ref.: https://opendev.org/openstack/horizon/src/branch/master/openstack_dashboard/static/app/core/keypairs/actions/create.service.js#L53
  openstack.cloud.keypair: "{{ item
    | combine({} if 'auth' in item else {'auth': openstack_auth})
    | combine({} if 'cloud' in item else {'cloud': openstack_cloud})
    | combine({} if 'interface' in item else {'interface': openstack_interface})
    | combine({} if 'name' in item else {'name': (item.comment if 'comment' in item else item.user) | regex_replace('[^A-Za-z0-9 _-]', '')})
    | combine({} if 'public_key' in item or 'key' not in item else {'public_key': item.key})
  }}"
