---
# Copyright (c) 2020-2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Add/Modify/Remove OpenStack block storage volumes
  loop: "{{ openstack_volumes|default([]) }}"
  openstack.cloud.volume: "{{ item
    |combine({} if 'auth' in item else {'auth': openstack_auth})
    |combine({} if 'cloud' in item else {'cloud': openstack_cloud})
    |combine({} if 'interface' in item else {'interface': openstack_interface})
  }}"
