galaxy_info:
  role_name: storage
  author: Jakob Meng
  description: Manage partitions, encrypted (LUKS) devices, LVM volume groups, LVM volumes, filesystems and mountpoints
  company: Hochschule Bonn-Rhein-Sieg
  license: license (GPLv3)

  min_ansible_version: '2.9'

  platforms:
  # Ref.: https://galaxy.ansible.com/api/v1/platforms/
  - name: Debian
    versions:
    - buster
    - bullseye
    - bookworm
    - trixie
    - sid

  - name: EL
    versions:
    - '7'
    - '8'
    - '9'

  - name: Fedora

  - name: Ubuntu
    versions:
    - bionic
    - focal
    - jammy
    - noble

  galaxy_tags:
  - development
  - system

dependencies: []
