---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Change blocks in Netplan configuration
  loop: '{{ netplan_config|default([]) }}'
  when: "'blockinfile' in item"
  blockinfile: "{{ item['blockinfile'] }}"
  register: netplan_config_blockinfile_result
  notify:
  - 'Apply Netplan configuration'

- name: Copy files to Netplan configuration
  loop: '{{ netplan_config|default([]) }}'
  when: "'copy' in item"
  copy: "{{ item['copy'] }}" # noqa risky-file-permissions
  register: netplan_config_copy_result
  notify:
  - 'Apply Netplan configuration'

- name: Change debconf selections for Netplan
  loop: '{{ netplan_config|default([]) }}'
  when: "'debconf' in item"
  debconf: "{{ item['debconf'] }}"
  register: netplan_config_debconf_result
  notify:
  - 'Apply Netplan configuration'

- name: Manage files in Netplan configuration
  loop: '{{ netplan_config|default([]) }}'
  when: "'file' in item"
  file: "{{ item['file'] }}"
  register: netplan_config_file_result
  notify:
  - 'Apply Netplan configuration'

- name: Change lines in Netplan configuration
  loop: '{{ netplan_config|default([]) }}'
  when: "'lineinfile' in item"
  lineinfile: "{{ item['lineinfile'] }}"
  register: netplan_config_lineinfile_result
  notify:
  - 'Apply Netplan configuration'

- name: Generate Netplan configuration from templates
  loop: '{{ netplan_config|default([]) }}'
  when: "'template' in item"
  template: "{{ item['template'] }}" # noqa risky-file-permissions
  register: netplan_config_template_result
  notify:
  - 'Apply Netplan configuration'

- name: Apply Netplan configuration now
  meta: flush_handlers

- name: Debug role variables
  debug:
    msg:
      netplan_config_blockinfile_result: '{{ netplan_config_blockinfile_result }}'
      netplan_config_copy_result: '{{ netplan_config_copy_result }}'
      netplan_config_debconf_result: '{{ netplan_config_debconf_result }}'
      netplan_config_file_result: '{{ netplan_config_file_result }}'
      netplan_config_lineinfile_result: '{{ netplan_config_lineinfile_result }}'
      netplan_config_template_result: '{{ netplan_config_template_result }}'
  tags:
    - never
    - debug
