---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Add/Modify/Delete users
  loop: '{{ users_config|default([]) }}'
  ansible.builtin.user: '{{ item }}'
  register: users_config_user_result

- name: Debug role variables
  debug:
    msg:
      users_config_user_result: '{{ users_config_user_result }}'
  tags:
    - never
    - debug
