---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# Ansible modules kernel_blacklist and modprobe are not listed here because their behaviour can be emulated easily.
# For example, to load kernel modules add them to /etc/modules with Ansible's blockinfile module, an Ansible handler
# will reboot the system after applying the changes after which all kernel modules will be loaded. To blacklist kernel
# modules add them to a file /etc/modprobe.d/blacklist-*.conf, an Ansible handler will then reboot the system.

- name: Change blocks in files
  loop: '{{ initrd_config|default([]) }}'
  when: "'blockinfile' in item"
  blockinfile: "{{ item['blockinfile'] }}"
  register: initrd_config_blockinfile_result
  notify:
  - 'Generate initramfs images'

- name: Copy files
  loop: '{{ initrd_config|default([]) }}'
  when: "'copy' in item"
  copy: "{{ item['copy'] }}"
  register: initrd_config_copy_result
  notify:
  - 'Generate initramfs images'

- name: Manage files
  loop: '{{ initrd_config|default([]) }}'
  when: "'file' in item"
  file: "{{ item['file'] }}"
  register: initrd_config_file_result
  notify:
  - 'Generate initramfs images'

- name: Change lines in files
  loop: '{{ initrd_config|default([]) }}'
  when: "'lineinfile' in item"
  lineinfile: "{{ item['lineinfile'] }}"
  register: initrd_config_lineinfile_result
  notify:
  - 'Generate initramfs images'

- name: Generate files from templates
  loop: '{{ initrd_config|default([]) }}'
  when: "'template' in item"
  template: "{{ item['template'] }}"
  register: initrd_config_template_result
  notify:
  - 'Generate initramfs images'

- name: Debug role variables
  debug:
    msg:
      initrd_config_blockinfile_result: '{{ initrd_config_blockinfile_result }}'
      initrd_config_copy_result: '{{ initrd_config_copy_result }}'
      initrd_config_file_result: '{{ initrd_config_file_result }}'
      initrd_config_lineinfile_result: '{{ initrd_config_lineinfile_result }}'
      initrd_config_template_result: '{{ initrd_config_template_result }}'
  tags:
    - never
    - debug
