galaxy_info:
  role_name: podman
  author: Jakob Meng
  description: Manage pods, containers and images with Podman
  license: license (GPLv3)

  min_ansible_version: '2.9'

  platforms:
  # Ref.: https://galaxy.ansible.com/api/v1/platforms/
  - name: Debian
    versions:
    - bullseye
    - bookworm
    - trixie
    - sid

  - name: EL
    versions:
    - '8'
    - '9'

  - name: Fedora

  - name: Ubuntu
    versions:
    - jammy
    - noble

  galaxy_tags:
  - development
  - system

dependencies: []
