---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: 'Restart DHCP IPv4 service to apply changes'
  when: dhcpd_service_state != 'stopped'
  service:
    name: '{{ dhcpd_service_name }}'
    state: restarted

- name: 'Restart DHCP IPv6 service to apply changes'
  when: dhcpd6_service_state != 'stopped'
  service:
    name: '{{ dhcpd6_service_name }}'
    state: restarted
