---
# Copyright (c) 2021-2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Verify task definitions specified in httpd_config variable
  when: item is not mapping or (item.keys() | difference(['when'])) | list | length != 1
  ansible.builtin.fail:
    msg: >-
      Unsupported keyword or multiple module definitions found:
      {{ (item.keys() | difference(['when'])) | join(', ') }}.
  loop: '{{ httpd_config | default([]) }}'

- name: Install dependencies of collection jm1.pkg
  ansible.builtin.import_role:
    name: jm1.pkg.setup # If Ansible raises "ERROR! the role 'jm1.pkg.setup' was not found" then you might use the
                        # ansible-galaxy and the provided requirements.yml to install all missing role dependencies.

- name: Satisfy requirements on CentOS and Red Hat Enterprise Linux
  when: distribution_id | first in ['CentOS', 'Red Hat Enterprise Linux']
  jm1.pkg.meta_pkg:
    name: "jm1-cloudy-httpd"
    version: "1"
    depends:
    - httpd

- name: Satisfy requirements on Debian and Ubuntu
  when: distribution_id | first in ['Debian', 'Ubuntu']
  jm1.pkg.meta_pkg:
    name: "jm1-cloudy-httpd"
    version: "1"
    depends:
    - apache2

- name: Run tasks specified in httpd_config variable
  jm1.ansible.execute_module:
    name: "{{ (item.keys() | difference(['when'])) | first }}"
    args: "{{ item[(item.keys() | difference(['when'])) | first] }}"
    when: "{{ item['when'] | default(omit) }}"
  loop: "{{ httpd_config | default([]) }}"
  notify:
  - 'Restart httpd service to apply changes'

- name: Manage httpd service
  ansible.builtin.service:
    enabled: '{{ httpd_service_enabled }}'
    name: '{{ httpd_service_name }}'
    state: '{{ httpd_service_state }}'
