galaxy_info:
  role_name: libvirt_domain_state
  author: Jakob Meng
  description: Manage libvirt domain states
  company: Hochschule Bonn-Rhein-Sieg
  license: license (GPLv3)

  min_ansible_version: 2.9

  platforms:
  # Ref.: https://galaxy.ansible.com/api/v1/platforms/
  - name: Debian
    versions:
    - buster
    - bullseye
    - bookworm

  - name: EL
    versions:
    - 7
    - 8

  - name: Ubuntu
    versions:
    - bionic
    - focal

  galaxy_tags:
  - development
  - system

dependencies: []
