---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Manage partitions, encrypted (LUKS) devices, LVM volume groups, LVM volumes, filesystems and mountpoints
  # The user may choose freely in which order partitions, encrypted (LUKS) devices, LVM volume groups, LVM volumes,
  # filesystems and mountpoints are created. To support this degree of freedom the order of actions must not be
  # predefined. Instead user-defined variable 'storage_config' defines a list of actions which describes what to do.
  # This task loops over this list and runs file setup.yml for each list item. Each list item represents a single action
  # such as creating a partition which is run by a matching Ansible module in setup.yml.
  loop: '{{ storage_config|default([]) }}'
  include_tasks: setup.yml
  register: storage_config_result

- name: Force changes to be applied now
  meta: flush_handlers

- name: Debug role variables
  debug:
    msg:
      storage_config_result: '{{ storage_config_result }}'
  tags:
    - never
    - debug
