---
# Copyright (c) 2020-2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Verify task definitions specified in storage_config variable
  when: item is not mapping or (item.keys()|difference(['register', 'when']))|list|length != 1
  ansible.builtin.fail:
    msg: >-
      Unsupported keyword or multiple module definitions found:
      {{ (item.keys()|difference(['register', 'when']))|join(', ') }}.
  loop: '{{ storage_config|default([]) }}'

- name: Manage partitions, encrypted (LUKS) devices, LVM volume groups, LVM volumes, filesystems and mountpoints
  # The user may choose freely in which order partitions, encrypted (LUKS) devices, LVM volume groups, LVM volumes,
  # filesystems and mountpoints are created. To support this degree of freedom the order of actions must not be
  # predefined. Instead user-defined variable 'storage_config' defines a list of actions which describes what to do.
  # This task loops over this list and runs file setup.yml for each list item. Each list item represents a single action
  # such as creating a partition which is run by a matching Ansible module in setup.yml.
  loop: '{{ storage_config|default([]) }}'
  ansible.builtin.include_tasks: setup.yml

- name: Force changes to be applied now
  ansible.builtin.meta: flush_handlers
