---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Manage block device partitions
  when: "'parted' in item"
  parted: "{{ item }}"
  notify:
  - 'Reboot after partitions, encrypted (LUKS) devices, LVM devices, filesystems or mountpoints have been changed'

- name: Manage encrypted (LUKS) devices
  when: "'luks_device' in item"
  luks_device: "{{ item }}"
  notify:
  - 'Reboot after partitions, encrypted (LUKS) devices, LVM devices, filesystems or mountpoints have been changed'

- name: Manage LVM volume groups
  when: "'lvg' in item"
  lvg: "{{ item }}"
  notify:
  - 'Reboot after partitions, encrypted (LUKS) devices, LVM devices, filesystems or mountpoints have been changed'

- name: Manage LVM logical volumes
  when: "'lvol' in item"
  lvol: "{{ item }}"
  notify:
  - 'Reboot after partitions, encrypted (LUKS) devices, LVM devices, filesystems or mountpoints have been changed'

- name: Manage entries in /etc/crypttab
  when: "'crypttab' in item"
  crypttab: "{{ item }}"
  notify:
  - 'Reboot after partitions, encrypted (LUKS) devices, LVM devices, filesystems or mountpoints have been changed'

- name: Manage entries in /etc/crypttab
  when: "'crypttab' in item"
  crypttab: "{{ item }}"
  notify:
  - 'Reboot after partitions, encrypted (LUKS) devices, LVM devices, filesystems or mountpoints have been changed'

- name: Manage entries in /etc/fstab
  when: "'mount' in item"
  mount: "{{ item }}"
  notify:
  - 'Reboot after partitions, encrypted (LUKS) devices, LVM devices, filesystems or mountpoints have been changed'

- name: Force changes to be applied now
  when: "'meta' in item and item.meta == 'flush_handlers'"
  meta: flush_handlers
