---
# Copyright (c) 2020-2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Run task specified in item variable
  when: "item not in [{'meta': 'flush_handlers'}, {'ansible.builtin.meta': 'flush_handlers'}]"
  jm1.ansible.execute_module:
    name: "{{ (item.keys() | difference(['when'])) | first }}"
    args: "{{ item[(item.keys() | difference(['when'])) | first] }}"
    when: "{{ item['when'] | default(omit) }}"
  notify:
  - 'Reboot after partitions, encrypted (LUKS) devices, LVM devices, filesystems or mountpoints have been changed'

- name: Force changes to be applied now
  when: "item in [{'meta': 'flush_handlers'}, {'ansible.builtin.meta': 'flush_handlers'}]"
  ansible.builtin.meta: flush_handlers
