---
# Copyright (c) 2023 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: 'Run Podman handlers to apply changes'
  loop: "{{ podman_config_result.results | subelements('item.handlers', skip_missing=True) }}"
  when: item.0.changed
  jm1.ansible.execute_module:
    name: "{{ (item.1.keys() | difference(['register', 'when'])) | first }}"
    args: "{{ item.1[(item.1.keys() | difference(['register', 'when'])) | first] }}"
    register: "{{ item.1['register'] | default(omit) }}"
    when: item.1['when'] | default(omit)
