---
# Copyright (c) 2023 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: 'Run Podman handlers to apply changes'
  loop: "{{ podman_handlers | default([]) }}"
  jm1.ansible.execute_module:
    name: "{{ (item.keys() | difference(['when'])) | first }}"
    args: "{{ item[(item.keys() | difference(['when'])) | first] }}"
    when: "{{ item['when'] | default(omit) }}"
  notify:
  - 'Reset Podman related handlers'

- name: 'Reset Podman related handlers'
  ansible.builtin.set_fact:
    podman_handlers: []
