---
# Copyright (c) 2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Change blocks in NetworkManager configuration
  loop: '{{ networkmanager_config|default([]) }}'
  when: "'blockinfile' in item"
  blockinfile: "{{ item['blockinfile'] }}"
  register: networkmanager_config_blockinfile_result
  notify:
  - 'Reboot to apply NetworkManager configuration changes'

- name: Copy files to NetworkManager configuration
  loop: '{{ networkmanager_config|default([]) }}'
  when: "'copy' in item"
  copy: "{{ item['copy'] }}" # noqa risky-file-permissions
  register: networkmanager_config_copy_result
  notify:
  - 'Reboot to apply NetworkManager configuration changes'

- name: Change debconf selections for NetworkManager
  loop: '{{ networkmanager_config|default([]) }}'
  when: "'debconf' in item"
  debconf: "{{ item['debconf'] }}"
  register: networkmanager_config_debconf_result
  notify:
  - 'Reboot to apply NetworkManager configuration changes'

- name: Manage files in NetworkManager configuration
  loop: '{{ networkmanager_config|default([]) }}'
  when: "'file' in item"
  file: "{{ item['file'] }}"
  register: networkmanager_config_file_result
  notify:
  - 'Reboot to apply NetworkManager configuration changes'

- name: Change lines in NetworkManager configuration
  loop: '{{ networkmanager_config|default([]) }}'
  when: "'lineinfile' in item"
  lineinfile: "{{ item['lineinfile'] }}"
  register: networkmanager_config_lineinfile_result
  notify:
  - 'Reboot to apply NetworkManager configuration changes'

- name: Change NetworkManager configuration
  loop: '{{ networkmanager_config|default([]) }}'
  when: "'nmcli' in item"
  nmcli: "{{ item['nmcli'] }}"
  register: networkmanager_config_nmcli_result
  # nmcli applies changes immediately so no handler has to be notified

- name: Generate NetworkManager configuration from templates
  loop: '{{ networkmanager_config|default([]) }}'
  when: "'template' in item"
  template: "{{ item['template'] }}" # noqa risky-file-permissions
  register: networkmanager_config_template_result
  notify:
  - 'Reboot to apply NetworkManager configuration changes'

- name: Reboot to apply NetworkManager configuration changes now
  meta: flush_handlers

- name: Debug role variables
  debug:
    msg:
      networkmanager_config_blockinfile_result: '{{ networkmanager_config_blockinfile_result }}'
      networkmanager_config_copy_result: '{{ networkmanager_config_copy_result }}'
      networkmanager_config_debconf_result: '{{ networkmanager_config_debconf_result }}'
      networkmanager_config_file_result: '{{ networkmanager_config_file_result }}'
      networkmanager_config_lineinfile_result: '{{ networkmanager_config_lineinfile_result }}'
      networkmanager_config_nmcli_result: '{{ networkmanager_config_nmcli_result }}'
      networkmanager_config_template_result: '{{ networkmanager_config_template_result }}'
  tags:
    - never
    - debug
