---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# TODO: Once Netplan support has been implemented, try to extract host's ip address
#       from Netplan config because hostname might not be DNS resolvable.
#ansible_host: "{{ cldy_netplan_config['ethernets']['eth0']['addresses'][0]|ansible.utils.ipaddr('address')
#                  if cldy_netplan_config['ethernets']['eth0']['addresses'][0]|default(None) != None else inventory_hostname }}"

# Possible power states: ['on', 'off']
# Ref.: https://docs.ansible.com/ansible/latest/collections/community/general/ipmi_power_module.html
ipmi_power_state: 'on'
