---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# Try to extract host's ip address from Netplan config because hostname might not be DNS resolvable.
ansible_host: "{{ openstack_netplan['ethernets']['eth0']['addresses'][0]|default('')|ipaddr('address')|default(openstack_server_name) }}"

cloudinit_userdata: |
  {{ cloudinit_userdata_default }}

  runcmd:
  # Copied from cloudinit_userdata_default because its runcmd list is overridden here.
  # Lists or dictionaries in YAML files are not merged, hence in case of multiple entries
  # with the same key all but the last one are ignored.
  {% if distribution_id|first == 'Ubuntu' %}
  - ln -s /dev/null /etc/systemd/network/99-default.link
  - update-initramfs -u -k all
  {% endif %}
  #
  - usermod -U ansible
  - passwd -d ansible

# distribution_id is set in host_vars

# openstack_auth is set in cloud-specific group_vars

# openstack_cloud is set in cloud-specific group_vars

# openstack_compute_flavors is set in cloud-specific group_vars
# NOTE: Regular users are not allowed to define compute flavors!

openstack_interface: '{{ omit }}'

openstack_keypairs: "{{ ssh_authorized_keys|selectattr('user', 'equalto', ansible_user)|selectattr('state', 'equalto', 'present')|list }}"

# openstack_netplan is generated in role openstack_server resp. openstack_server_netplan

# openstack_network_ports is set in host_vars

openstack_server_auto_ip: no

# openstack_server_boot_from_volume is not set

openstack_server_boot_volume: '{{ openstack_volumes|first if openstack_volumes is defined and openstack_volumes|length > 0 else None }}'

openstack_server_config_drive: no

# openstack_server_delete_fip is not set

openstack_server_flavor: 'c2.m4'

# openstack_server_flavor_include is not set

# openstack_server_flavor_ram is not set

# openstack_server_floating_ip_pools is not set

# openstack_server_floating_ips is set in host_vars

# openstack_server_image is not set

# openstack_server_image_exclude is not set

openstack_server_images:
  CentOS_7: 'CentOS-7-x86_64-GenericCloud-2003.raw'
  CentOS_8: 'CentOS-8-GenericCloud-8.2.2004-20200611.2.x86_64.raw'
  Debian_10: 'debian-10.4.2-20200608-openstack-amd64.raw'
  #Debian_11: 'debian-11-********-openstack-amd64.raw'
  Ubuntu_18_04: 'ubuntu-18.04-server-cloudimg-amd64-20200908.raw'
  #Ubuntu_20_04: 'ubuntu-20.04-server-cloudimg-amd64-20200616.raw'
  Ubuntu_20_04: 'ubuntu-20.04-server-cloudimg-amd64-20201102.raw'

# openstack_server_key_name is not set, because it is set using cloudinit_userdata aka openstack_server_userdata

# openstack_server_meta is not set

openstack_server_name: '{{ fqdn }}'

# openstack_server_network is not set

# openstack_server_reuse_ips is not set

# openstack_server_scheduler_hints is not set

openstack_server_security_groups:
- default

openstack_server_terminate_volume: no

# Possible server states: [active, paused, suspended, shutoff, shelved, shelved_offloaded]
# Ref.: https://docs.openstack.org/api-guide/compute/server_concepts.html
openstack_server_state: active

openstack_server_userdata: '{{ cloudinit_userdata }}'

# openstack_server_volume_size is not set

openstack_server_volumes: '{{ openstack_volumes[1:] if openstack_volumes is defined and openstack_volumes|length > 1 else [] }}'

openstack_volumes:
- bootable: yes
  display_name: '{{ openstack_server_name }}'
  image: "{{ openstack_server_images[distribution_id|join('_')|regex_replace('[^A-Za-z0-9 _-]', '_')] }}"
  size: 10
  state: present
