---
# Copyright (c) 2020-2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

ansible_host: "{{ openstack_server_name }}"

cloudinit_userdata: |
  {{ cloudinit_userdata_default }}

  runcmd:
  # Copied from cloudinit_userdata_default because its runcmd list is overridden here.
  # Lists or dictionaries in YAML files are not merged, hence in case of multiple entries
  # with the same key all but the last one are ignored.
  {% if distribution_id | first == 'Ubuntu' %}
  - ln -s /dev/null /etc/systemd/network/99-default.link
  - update-initramfs -u -k all
  {% endif %}
  #
  - usermod -U ansible
  - passwd -d ansible

# distribution_id is set in host_vars

# openstack_auth, openstack_cloud and openstack_interface are set in cloud-specific group_vars

# OpenStack compute flavors are defined in cloud-specific group_vars
# NOTE: Regular users are not allowed to define compute flavors!

openstack_keypairs: "{{ ssh_authorized_keys | selectattr('user', 'equalto', ansible_user) | selectattr('state', 'equalto', 'present') | list }}"

openstack_server_config:
  auto_ip: no
  boot_volume: '{{ openstack_volumes | first if openstack_volumes is defined and openstack_volumes | length > 0 else None }}'
  config_drive: no
  flavor: 'c2.m4'
  # key_name is not set because it is set using cloudinit_userdata
  security_groups:
  - default
  terminate_volume: no
  userdata: '{{ cloudinit_userdata }}'
  volumes: '{{ openstack_volumes[1:] if openstack_volumes is defined and openstack_volumes | length > 1 else [] }}'

openstack_server_images:
  CentOS_7: 'CentOS-7-x86_64-GenericCloud-2003-bios'
  CentOS_8: 'CentOS-Stream-GenericCloud-8-20210603.0.x86_64-bios'
  CentOS_9: 'CentOS-Stream-GenericCloud-9-20220127.0.x86_64-bios'
  Debian_10: 'debian-10-genericcloud-amd64-bios'
  Debian_11: 'debian-11-genericcloud-amd64-bios'
  Ubuntu_18_04: 'ubuntu-18.04-server-cloudimg-amd64-bios'
  Ubuntu_20_04: 'ubuntu-20.04-server-cloudimg-amd64-bios'

openstack_server_name: '{{ fqdn }}'

# NOTE: Variable openstack_server_state has to be defined in this inventory else grouping by openstack_server_state in
#       playbooks/site.yml fails because openstack_server_state is undefined.
# Possible server states: [active, paused, suspended, shutoff, shelved, shelved_offloaded]
# Ref.: https://docs.openstack.org/api-guide/compute/server_concepts.html
openstack_server_state: active

openstack_volumes:
- openstack.cloud.volume:
    bootable: yes
    display_name: '{{ openstack_server_name }}'
    image: "{{ openstack_server_images[distribution_id | join('_') | regex_replace('[^A-Za-z0-9_]', '_')] }}"
    size: 10
    state: present
