---
# Copyright (c) 2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

#dhcpd_authoritative: no
#
#dhcpd_distribution_filename_map: '{{ pxe_installer_distribution_filename_map }}'
#
#dhcpd_config: |
#  # 2021 Jakob Meng, <jakobmeng@web.de>
#  #
#  # Configuration file for ISC dhcpd
#  #
#  # NOTE: On Ubuntu, if /etc/ltsp/dhcpd.conf exists, that will be used as configuration file instead of this file.
#
#  # option definitions common to all supported networks...
#  {% for dhcpd_option in dhcpd_options %}
#  option {{ dhcpd_option }};
#  {% endfor %}
#
#  default-lease-time {{ dhcpd_default_lease_time }};
#  max-lease-time {{ dhcpd_max_lease_time }};
#
#  # The ddns-updates-style parameter controls whether or not the server will
#  # attempt to do a DNS update when a lease is confirmed. We default to the
#  # behavior of the version 2 packages ('none', since DHCP v2 didn't
#  # have support for DDNS.)
#  ddns-update-style none;
#
#  # If this DHCP server is the official DHCP server for the local
#  # network, the authoritative directive should be uncommented.
#  {{ 'authoritative;' if dhcpd_authoritative else '#authoritative;' }}
#
#  # Use this to send dhcp log messages to a different log file (you also
#  # have to hack syslog.conf to complete the redirection).
#  log-facility local7;
#
#  {% for
#  {% for dhcpd_group in dhcpd_groups %}
#  group {
#  {% for dhcpd_subnet in dhcpd_group['subnets']|default([]) %}
#    subnet dhcpd_subnet.number netmask dhcpd_subnet.netmask {
#  {% if filename in dhcpd_subnet %}
#      filename "{{ dhcpd_subnet.filename }}";
#  {% endif %}
#  {% for dhcpd_subnet_range in dhcpd_subnet['ranges']|default([]) %}
#      range {{ dhcpd_subnet_range }};
#  {% endfor %}
#  {% for dhcpd_option in dhcpd_subnet['options']|default([]) %}
#      option {{ dhcpd_option }};
#  {% endfor %}
#  {% for dhcpd_host in dhcpd_subnet['hosts']|default([]) %}
#      host {{ dhcpd_host.hostname }} {
#  {% for dhcpd_hardware in dhcpd_host['hardwares']|default([]) %}
#        hardware {{ dhcpd_hardware }};
#  {% endfor %}
#  {% for dhcpd_fixed_address in dhcpd_host['fixed_addresses']|default([]) %}
#        fixed-address {{ dhcpd_fixed_address }};
#  {% endfor %}
#      } # hostname
#  {% endfor %}
#    } # subnet
#  {% endfor %}
#  } # group
#  {% endfor %}
#
#dhcpd_default_lease_time: 43200
#
#dhcpd_groups: []
#
#dhcpd_max_lease_time: 86400
#
#dhcpd_options: []
#
