---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

openstack_auth: '{{ omit }}'

openstack_cloud: '{{ omit }}'

openstack_interface: '{{ omit }}'

openstack_server_name: '{{ fqdn|mandatory }}'

# Possible server states: [active, paused, suspended, shutoff, shelved, shelved_offloaded]
# Ref.: https://docs.openstack.org/api-guide/compute/server_concepts.html
openstack_server_state: active

state: present
