---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Install, upgrade or remove meta packages
  when: meta_packages is iterable and meta_packages is not mapping # list
  loop: '{{ meta_packages if meta_packages is iterable and meta_packages is not mapping else [] }}'
  jm1.pkg.meta_pkg: '{{ item }}'
  register: meta_packages_list_result

- name: Install, upgrade or remove meta packages
  when: meta_packages is mapping # dictionary
  jm1.pkg.meta_pkg: '{{ item }}'
  register: meta_packages_dict_result

- name: Debug role variables
  debug:
    msg:
      meta_packages_list_result: '{{ meta_packages_list_result }}'
      meta_packages_dict_result: '{{ meta_packages_dict_result }}'
  tags:
    - never
    - debug
