---
# Copyright (c) 2020-2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Install dependencies of collection jm1.pkg
  ansible.builtin.import_role:
    name: jm1.pkg.setup # If Ansible raises "ERROR! the role 'jm1.pkg.setup' was not found" then you might use the
                        # ansible-galaxy and the provided requirements.yml to install all missing role dependencies.
  when: meta_packages | length > 0 # is not empty

- name: Install, upgrade or remove meta packages
  when: meta_packages is iterable and meta_packages is not mapping # list
  loop: '{{ meta_packages if meta_packages is iterable and meta_packages is not mapping else [] }}'
  jm1.pkg.meta_pkg: '{{ item }}'

- name: Install, upgrade or remove meta packages
  when: meta_packages is mapping # dictionary
  jm1.pkg.meta_pkg: '{{ item }}'
