---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: 'Reconfigure debian packages to apply debconf database changes'
  loop: '{{ debconf_list_result.results }}'
  when: item.changed and debconf_reconfigure
  command:
    cmd: dpkg-reconfigure -f noninteractive '{{ item.item.name }}'

- name: 'Reconfigure debian package to apply debconf database changes'
  when: debconf_reconfigure
  command:
    cmd: dpkg-reconfigure -f noninteractive '{{ debconf_config.name }}'
