---
# Copyright (c) 2021-2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Verify task definitions specified in files_config variable
  when: item is not mapping or (item.keys()|difference(['register', 'when']))|list|length != 1
  ansible.builtin.fail:
    msg: >-
      Unsupported keyword or multiple module definitions found:
      {{ (item.keys()|difference(['register', 'when']))|join(', ') }}.
  loop: '{{ files_config|default([]) }}'

- name: Run tasks specified in files_config variable
  jm1.ansible.execute_module:
    name: "{{ (item.keys()|difference(['register', 'when']))|first }}"
    args: "{{ item[(item.keys()|difference(['register', 'when']))|first] }}"
    register: "{{ item['register']|default(omit) }}"
    when: item['when']|default(omit)
  loop: "{{ files_config|default([]) }}"
